presets:
- labels:
    preset-azure-secrets-store-creds: "true"
  env:
  - name: AZURE_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: azure-secrets-store-cred
        key: clientid
  - name: AZURE_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: azure-secrets-store-cred
        key: clientsecret
  - name: TENANT_ID
    valueFrom:
      secretKeyRef:
        name: azure-secrets-store-cred
        key: tenantid
- labels:
    preset-akeyless-secrets-store-creds: "true"
  env:
  - name: AKEYLESS_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: akeyless-test-cred
        key: credentials
