periodics:
- interval: 12h
  name: periodic-secrets-store-csi-driver-upgrade-test-azure-release-1-2
  decorate: true
  decoration_config:
    timeout: 30m
  labels:
    # this is required because we want to run kind in docker
    preset-dind-enabled: "true"
    # this is required to make CNI installation to succeed for kind
    preset-kind-volume-mounts: "true"
    # sets up the azure keyvault parameters used for testing
    preset-azure-secrets-store-creds: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: secrets-store-csi-driver
    base_ref: release-1.2
    path_alias: sigs.k8s.io/secrets-store-csi-driver
  spec:
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
        command:
          - runner.sh
        args:
          - bash
          - -c
          - >-
            make e2e-bootstrap e2e-helm-deploy-release e2e-azure && make e2e-helm-upgrade e2e-azure
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
  annotations:
    testgrid-dashboards: sig-auth-secrets-store-csi-driver, sig-auth-secrets-store-csi-driver-periodic
    testgrid-tab-name: secrets-store-csi-driver-upgrade-test-azure-release-1-2
    testgrid-alert-email: kubernetes-secrets-store-csi-driver@googlegroups.com
    description: "Run driver upgrade test with azure provider for Secrets Store CSI driver."
    testgrid-num-columns-recent: '30'
