presubmits:
  kubernetes-sigs/kueue:
  - name: pull-kueue-test-unit-main
    always_run: true
    decorate: true
    path_alias: sigs.k8s.io/kueue
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-kueue-test-unit-main
      description: "Run kueue unit tests"
    spec:
      containers:
      - image: golang:1.18
        env:
        - name: GO_TEST_FLAGS
          value: "-race -count 3"
        command:
        - make
        args:
        - test
  - name: pull-kueue-test-integration-main
    always_run: true
    decorate: true
    path_alias: sigs.k8s.io/kueue
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-kueue-test-integration-main
      description: "Run kueue test-integration"
    spec:
      containers:
      - image: golang:1.18
        command:
        - make
        args:
        - test-integration
  - name: pull-kueue-verify-main
    always_run: true
    decorate: true
    path_alias: sigs.k8s.io/kueue
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-kueue-verify-main
      description: "Run kueue verify checks"
    spec:
      containers:
      - image: golang:1.18
        command:
        - make
        args:
        - verify
  - name: pull-kueue-build-image-main
    always_run: true
    decorate: true
    path_alias: sigs.k8s.io/kueue
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-kueue-build-image-main
      description: "Build container image of kueue"
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        securityContext:
          privileged: true
        command:
        - runner.sh
        args:
        - make
        - image-build
