presets:
- labels:
    preset-capz-windows-common-124: "true"
  env:
  - name: "KUBERNETES_VERSION"
    value: "latest-1.24"
  - name: E2E_ARGS
    value: "-kubetest.use-ci-artifacts"
  - name: WINDOWS
    value: "true"
  - name: AZURE_NODE_MACHINE_TYPE
    value: "Standard_D4s_v3"
periodics:
- name: ci-kubernetes-e2e-capz-master-containerd-windows-1-24
  interval: 3h
  decorate: true
  decoration_config:
    timeout: 4h0m0s
  labels:
    preset-azure-cred-only: "true"
    preset-capz-containerd-latest: "true"
    preset-capz-windows-2019: "true"
    preset-capz-windows-common-124: "true"
    preset-capz-windows-parallel: "true"
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  extra_refs:
  - base_ref: main
    org: kubernetes-sigs
    path_alias: sigs.k8s.io/cluster-api-provider-azure
    repo: cluster-api-provider-azure
  spec:
    containers:
    - command:
      - runner.sh
      - ./scripts/ci-conformance.sh
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
      name: ""
      resources:
        requests:
          cpu: "2"
          memory: 9Gi
      securityContext:
        privileged: true
  annotations:
    testgrid-alert-email: kubernetes-provider-azure@googlegroups.com, sig-windows-leads@kubernetes.io
    testgrid-dashboards: sig-release-1.24-informing, sig-windows-1.24-release, sig-windows-signal
    testgrid-tab-name: capz-windows-containerd-1.24
- name: ci-kubernetes-e2e-capz-master-containerd-windows-serial-slow-1-24
  interval: 24h
  decorate: true
  decoration_config:
    timeout: 4h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-azure-cred-only: "true"
    preset-capz-windows-common-124: "true"
    preset-capz-windows-2019: "true"
    preset-capz-containerd-latest: "true"
    preset-capz-serial-slow: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-azure
    base_ref: main
    path_alias: sigs.k8s.io/cluster-api-provider-azure
  spec:
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
        command:
          - "runner.sh"
          - "./scripts/ci-conformance.sh"
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 2
            memory: "9Gi"
  annotations:
    testgrid-alert-email: kubernetes-provider-azure@googlegroups.com, sig-windows-leads@kubernetes.io
    testgrid-dashboards: sig-windows-1.24-release
    testgrid-tab-name: capz-windows-containerd-serial-slow-1.24
- name: ci-kubernetes-e2e-azure-disk-windows-containerd-1-24
  interval: 48h
  decorate: true
  decoration_config:
    timeout: 2h
  labels:
    preset-service-account: "true"
    preset-azure-cred: "true"
    preset-azure-windows: "true"
    preset-k8s-ssh: "true"
    preset-dind-enabled: "true"
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: release-1.24
    path_alias: k8s.io/kubernetes
  - org: kubernetes-sigs
    repo: azuredisk-csi-driver
    base_ref: master
    path_alias: sigs.k8s.io/azuredisk-csi-driver
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
      command:
      - runner.sh
      - kubetest
      args:
      # Generic e2e test args
      - --test
      - --up
      - --down
      - --build=quick
      - --dump=$(ARTIFACTS)
      # Azure-specific test args
      - --deployment=aksengine
      - --provider=skeleton
      - --aksengine-admin-username=azureuser
      - --aksengine-admin-password=AdminPassw0rd
      - --aksengine-creds=$(AZURE_CREDENTIALS)
      - --aksengine-download-url=https://aka.ms/aks-engine/aks-engine-k8s-e2e.tar.gz
      - --aksengine-public-key=$(K8S_SSH_PUBLIC_KEY_PATH)
      - --aksengine-private-key=$(K8S_SSH_PRIVATE_KEY_PATH)
      - --aksengine-winZipBuildScript=$(WIN_BUILD)
      - --aksengine-orchestratorRelease=1.24
      - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/windows-testing/master/job-templates/kubernetes_containerd_1_24_csi_enabled.json
      - --aksengine-win-binaries
      - --aksengine-deploy-custom-k8s
      - --aksengine-agentpoolcount=2
      # Specific test args
      - --test-azure-disk-csi-driver
      securityContext:
        privileged: true
      env:
      - name: AZURE_STORAGE_DRIVER
        value: "kubernetes.io/azure-disk" # In-tree Azure disk storage class
      - name: TEST_WINDOWS
        value: "true"
  annotations:
    testgrid-dashboards: sig-windows-1.24-release
    testgrid-tab-name: aks-engine-windows-containerd-azure-disk-1.24
    testgrid-alert-email: kubernetes-provider-azure@googlegroups.com, sig-windows-leads@kubernetes.io
    description: Run Azure Disk e2e test with Azure Disk in a Windows cluster configured with CSI proxy and containerd.
- name: ci-kubernetes-e2e-azure-file-windows-containerd
  interval: 48h
  decorate: true
  decoration_config:
    timeout: 2h
  labels:
    preset-service-account: "true"
    preset-azure-cred: "true"
    preset-azure-windows: "true"
    preset-k8s-ssh: "true"
    preset-dind-enabled: "true"
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: release-1.24
    path_alias: k8s.io/kubernetes
  - org: kubernetes-sigs
    repo: azurefile-csi-driver
    base_ref: master
    path_alias: sigs.k8s.io/azurefile-csi-driver
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
      command:
      - runner.sh
      - kubetest
      args:
      # Generic e2e test args
      - --test
      - --up
      - --down
      - --build=quick
      - --dump=$(ARTIFACTS)
      # Azure-specific test args
      - --deployment=aksengine
      - --provider=skeleton
      - --aksengine-admin-username=azureuser
      - --aksengine-admin-password=AdminPassw0rd
      - --aksengine-creds=$(AZURE_CREDENTIALS)
      - --aksengine-download-url=https://aka.ms/aks-engine/aks-engine-k8s-e2e.tar.gz
      - --aksengine-public-key=$(K8S_SSH_PUBLIC_KEY_PATH)
      - --aksengine-private-key=$(K8S_SSH_PRIVATE_KEY_PATH)
      - --aksengine-winZipBuildScript=$(WIN_BUILD)
      - --aksengine-orchestratorRelease=1.24
      - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/windows-testing/master/job-templates/kubernetes_containerd_1_24_csi_enabled.json
      - --aksengine-win-binaries
      - --aksengine-deploy-custom-k8s
      - --aksengine-agentpoolcount=2
      # Specific test args
      - --test-azure-file-csi-driver
      securityContext:
        privileged: true
      env:
      - name: AZURE_STORAGE_DRIVER
        value: "kubernetes.io/azure-file" # In-tree Azure file storage class
      - name: TEST_WINDOWS
        value: "true"
  annotations:
    testgrid-dashboards: sig-windows-1.24-release
    testgrid-tab-name: aks-engine-windows-containerd-azure-file-1.24
    testgrid-alert-email: kubernetes-provider-azure@googlegroups.com, sig-windows-leads@kubernetes.io
    description: Run Azure File e2e test with Azure File in a Windows cluster configured with CSI proxy and containerd.
