postsubmits:
  kubernetes/k8s.io:
  - name: post-k8sio-deploy-prow-build-resources
    cluster: k8s-infra-prow-build-trusted
    decorate: true
    max_concurrency: 1
    run_if_changed: "^infra/gcp/terraform/k8s-infra-prow-build/"
    branches:
    - ^main$
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: sig-k8s-infra-prow
      testgrid-tab-name: deploy-prow-build
      testgrid-alert-email: k8s-infra-alerts@kubernetes.io
      testgrid-num-failures-to-alert: '1'
    rerun_auth_config:
      github_team_slugs:
      # proxy for sig-k8s-infra-oncall
      - org: kubernetes
        slug: sig-k8s-infra-leads
      # proxy for test-infra-oncall
      - org: kubernetes
        slug: test-infra-admins
    reporter_config:
      slack:
        channel: "prow-alerts"
        job_states_to_report:
        - success
        - failure
        - aborted
        - error
        report_template: 'Deploying k8s-infra-prow-build cluster: {{.Status.State}}. Commit: <{{.Spec.Refs.BaseLink}}|{{printf "%.7s" .Spec.Refs.BaseSHA}}> | <{{.Status.URL}}|Spyglass> | <https://testgrid.k8s.io/sig-k8s-infra-prow#deploy-prow-build|Testgrid> | <https://prow.k8s.io/?job={{.Spec.Job}}|Deck>'
    spec:
      serviceAccountName: prow-deployer
      containers:
      - image: gcr.io/k8s-staging-infra-tools/k8s-infra:latest
        command:
        - ./infra/gcp/terraform/k8s-infra-prow-build/deploy.sh
  - name: post-k8sio-deploy-prow-build-trusted-resources
    cluster: k8s-infra-prow-build-trusted
    decorate: true
    max_concurrency: 1
    run_if_changed: "^infra/gcp/terraform/k8s-infra-prow-build-trusted/"
    branches:
    - ^main$
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: sig-k8s-infra-prow
      testgrid-tab-name: deploy-prow-build-trusted
      testgrid-alert-email: k8s-infra-alerts@kubernetes.io
      testgrid-num-failures-to-alert: '1'
    rerun_auth_config:
      github_team_slugs:
      # proxy for sig-k8s-infra-oncall
      - org: kubernetes
        slug: sig-k8s-infra-leads
      # proxy for test-infra-oncall
      - org: kubernetes
        slug: test-infra-admins
    spec:
      serviceAccountName: prow-deployer
      containers:
      - image: gcr.io/k8s-staging-infra-tools/k8s-infra:latest
        command:
        - ./infra/gcp/terraform/k8s-infra-prow-build-trusted/deploy.sh
    reporter_config:
      slack:
        channel: "prow-alerts"
        job_states_to_report:
        - success
        - failure
        - aborted
        - error
        report_template: 'Deploying k8s-infra-prow-build-trusted cluster: {{.Status.State}}. Commit: <{{.Spec.Refs.BaseLink}}|{{printf "%.7s" .Spec.Refs.BaseSHA}}> | <{{.Status.URL}}|Spyglass> | <https://testgrid.k8s.io/sig-k8s-infra-prow#deploy-prow-build-trusted|Testgrid> | <https://prow.k8s.io/?job={{.Spec.Job}}|Deck>'

periodics:
- name: ci-k8s-infra-build-cluster-prow-build-trusted
  cron: "*/5 * * * *" #Every 5 minutes
  cluster: k8s-infra-prow-build-trusted
  decorate: true
  max_concurrency: 1
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
  annotations:
    testgrid-dashboards: sig-k8s-infra-prow
    testgrid-tab-name: gke-prow-build-trusted-heartbeat
    testgrid-num-failures-to-alert: '6'
    testgrid-alert-email: k8s-infra-alerts@kubernetes.io, k8s-infra-prow-oncall@kubernetes.io
  spec:
    containers:
    - image: gcr.io/k8s-staging-infra-tools/k8s-infra:latest
      command:
      - "echo"
      args:
      - "Everything is fine!"
      resources:
        limits:
          cpu: 100m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 512Mi

- name: ci-k8sio-autobump-prow-build-clusters
  cron: "15 14-20/5 * * 1-5"  # Run at :15 every hour between 9:15 and 6:15 PM PST Mon-Fri
  cluster: k8s-infra-prow-build-trusted
  decorate: true
  max_concurrency: 1
  extra_refs:
  - org: kubernetes
    repo: k8s.io
    base_ref: main
  annotations:
    testgrid-dashboards: sig-k8s-infra-k8sio
    testgrid-alert-email: k8s-infra-alerts@kubernetes.io
    testgrid-num-failures-to-alert: '3'
    description: runs autobumper to create/update a PR that updates prow build cluster component images
  rerun_auth_config:
    github_team_slugs:
    # proxy for sig-k8s-infra-oncall
    - org: kubernetes
      slug: sig-k8s-infra-leads
    # proxy for test-infra-oncall
    - org: kubernetes
      slug: test-infra-admins
  spec:
    containers:
    - image: gcr.io/k8s-prow/generic-autobumper:v20220819-de76c58889
      command:
      - generic-autobumper
      args:
      - --config=hack/autobump-config.yaml
      volumeMounts:
      - name: github
        mountPath: /etc/github-token
        readOnly: true
    volumes:
    - name: github
      secret:
        secretName: k8s-infra-ci-robot-github-token

- name: ci-k8sio-autobump-prow-build-clusters-for-autodeploy
  # This is arbitrarily 3h earlier than test-infra-oncall's prow autobump job
  cron: "30 14-19/5 * * 1-5"  # Run at 7:30 and 12:30 PST Mon-Fri
  cluster: k8s-infra-prow-build-trusted
  decorate: true
  max_concurrency: 1
  extra_refs:
  - org: kubernetes
    repo: k8s.io
    base_ref: main
  annotations:
    testgrid-dashboards: sig-k8s-infra-k8sio
    testgrid-alert-email: k8s-infra-alerts@kubernetes.io
    testgrid-num-failures-to-alert: '1'
    description: runs autobumper to create/update a PR that updates prow build cluster component images
  rerun_auth_config:
    github_team_slugs:
    # proxy for sig-k8s-infra-oncall
    - org: kubernetes
      slug: sig-k8s-infra-leads
    # proxy for test-infra-oncall
    - org: kubernetes
      slug: test-infra-admins
  spec:
    containers:
    - image: gcr.io/k8s-prow/generic-autobumper:v20220819-de76c58889
      command:
      - generic-autobumper
      args:
      - --config=hack/autobump-config.yaml
      - --labels-override=skip-review
      - --skip-if-no-oncall
      volumeMounts:
      - name: github
        mountPath: /etc/github-token
        readOnly: true
    volumes:
    - name: github
      secret:
        secretName: k8s-infra-ci-robot-github-token
