periodics:
- name: periodic-k8sio-deploy-app-codesearch
  cluster: k8s-infra-prow-build-trusted
  interval: 24h
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: k8s.io
    base_ref: main
  reporter_config:
    slack:
      channel: "k8s-infra-alerts"
      job_states_to_report:
      - failure
      - aborted
      - error
      report_template: 'Deploying codesearch: {{.Status.State}}. <{{.Status.URL}}|Spyglass> | <https://testgrid.k8s.io/sig-k8s-infra-apps#deploy-codesearch|Testgrid> | <https://prow.k8s.io/?job={{.Spec.Job}}|Deck>'
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: sig-k8s-infra-apps
    testgrid-tab-name: periodic-deploy-codesearch
    testgrid-description: 'runs https://git.k8s.io/k8s.io/apps/codesearch/deploy.sh daily in kubernetes/k8s.io/apps/codesearch'
    testgrid-alert-email: k8s-infra-rbac-codesearch@kubernetes.io, k8s-infra-alerts@kubernetes.io
    testgrid-num-failures-to-alert: '2'
  spec:
    serviceAccountName: prow-deployer
    containers:
    - image: gcr.io/k8s-staging-infra-tools/k8s-infra:latest
      imagePullPolicy: Always
      command:
      - ./apps/codesearch/deploy.sh
      volumeMounts:
      - name: github
        mountPath: /etc/github-token
        readOnly: true
    volumes:
    - name: github
      secret:
        secretName: k8s-infra-ci-robot-github-token
