postsubmits:
  kubernetes/test-infra:
  - name: post-test-infra-upload-triage
    cluster: k8s-infra-prow-build-trusted
    branches:
    - ^master$
    max_concurrency: 1
    run_if_changed: '^triage/Makefile$|^triage/[^/]+(\.html|\.js|\.css)$'
    decorate: true
    spec:
      serviceAccountName: k8s-triage
      containers:
      - image: gcr.io/k8s-staging-infra-tools/k8s-infra:latest
        command:
        - make
        args:
        - -C
        - ./triage/
        - push-static
        resources:
          requests:
            memory: "1Gi"
    annotations:
      testgrid-dashboards: sig-testing-maintenance, sig-k8s-infra-prow
      testgrid-tab-name: triage-update
      testgrid-alert-email: kubernetes-sig-testing-alerts@googlegroups.com, k8s-infra-alerts@kubernetes.io
      testgrid-num-failures-to-alert: '1'
      description: Updates the html contents for go.k8s.io/triage.

periodics:
- name: metrics-bigquery
  cron: "03 0-23/3 * * *"  # like interval: 6h, but explicitly starting at 00:03 UTC
  cluster: k8s-infra-prow-build-trusted
  decorate: true
  max_concurrency: 1
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
  annotations:
    testgrid-dashboards: sig-testing-misc, sig-k8s-infra-prow
    testgrid-alert-email: kubernetes-sig-testing-alerts@googlegroups.com, k8s-infra-alerts@kubernetes.io
    testgrid-num-failures-to-alert: '2'
    description: Runs BigQuery queries to generate data for metrics.
  rerun_auth_config:
    github_team_slugs:
    # proxy for sig-k8s-infra-oncall
    - org: kubernetes
      slug: sig-k8s-infra-leads
    # proxy for test-infra-oncall
    - org: kubernetes
      slug: test-infra-admins
  spec:
    serviceAccountName: k8s-metrics
    containers:
    - image: gcr.io/k8s-staging-test-infra/bigquery:v20220427-c2db0f69b7
      args:
      - ./metrics/bigquery.py
      - --bucket=gs://k8s-metrics
      - --project=k8s-infra-prow-build-trusted
      - --jq=/usr/bin/jq

- name: ci-test-infra-triage
  interval: 30m
  cluster: k8s-infra-prow-build-trusted
  decorate: true
  decoration_config:
    timeout: 3h
  max_concurrency: 1
  annotations:
    testgrid-num-failures-to-alert: '18'
    testgrid-alert-stale-results-hours: '12'
    testgrid-dashboards: sig-testing-misc, sig-k8s-infra-prow
    testgrid-tab-name: triage
    testgrid-alert-email: kubernetes-sig-testing-alerts@googlegroups.com, k8s-infra-alerts@kubernetes.io
    description: Runs BigQuery queries, summarizes results into clusters, and uploads to GCS for go.k8s.io/triage
  rerun_auth_config:
    github_team_slugs:
    # proxy for sig-k8s-infra-oncall
    - org: kubernetes
      slug: sig-k8s-infra-leads
    # proxy for test-infra-oncall
    - org: kubernetes
      slug: test-infra-admins
  spec:
    serviceAccountName: k8s-triage
    containers:
    - image: gcr.io/k8s-staging-test-infra/triage:latest
      imagePullPolicy: Always
      env:
      # Go incorrectly determines the number of CPUs in a pod, set manually to (2*CPUs-1)
      # TODO: determine the optimal number of workers, 2*CPU-1 is an assumption
      - name: NUM_WORKERS
        value: "13"
      - name: TRIAGE_DATASET_TABLE
        value: "kubernetes-public:k8s_triage.temp"
      - name: TRIAGE_TEMP_GCS_PATH
        value: "gs://k8s-triage/triage_tests"
      - name: TRIAGE_GCS_PATH
        value: "gs://k8s-triage"
      - name: TRIAGE_BQ_USAGE_PROJECT
        value: "k8s-infra-prow-build-trusted"
      command:
      - timeout
      args:
      - "10800"
      - /update_summaries.sh
      # When changing CPUs, also change NUM_WORKERS above
      resources:
        requests:
          cpu: 6
          memory: 32Gi
        limits:
          cpu: 6
          memory: 32Gi

- name: ci-test-infra-autobump-prowjobs
  cron: "06 14-23 * * 1-5"  # Run every hour at 7:06 - 16:06 PDT (in UTC) Mon-Fri
  cluster: k8s-infra-prow-build-trusted
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
  spec:
    containers:
    - image: gcr.io/k8s-prow/generic-autobumper:v20220819-de76c58889
      command:
      - generic-autobumper
      args:
      - --config=config/prow/autobump-config/prow-job-autobump-config.yaml
      volumeMounts:
      - name: github
        mountPath: /etc/github-token
        readOnly: true
    volumes:
    - name: github
      secret:
        secretName: k8s-infra-ci-robot-github-token
  annotations:
    testgrid-dashboards: sig-testing-prow
    testgrid-tab-name: autobump-prowjobs
    description: runs experiment/autobumper to create/update a PR that bumps prowjob images to latest published version
    testgrid-alert-email: k8s-infra-oncall@google.com
    testgrid-num-failures-to-alert: '3'
- name: ci-test-infra-autobump-prowjobs-for-auto-deploy
  # This 1h after ci-k8sio-autobump-prow-build-clusters, 2h before ci-test-infra-autobump-prow-for-auto-deploy
  cron: "30 15-20/5 * * 1-5"  # Bump with label `skip-review`. Run at 08:30 and 13:30 PDT (in UTC) Mon-Fri
  cluster: k8s-infra-prow-build-trusted
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
  spec:
    containers:
    - image: gcr.io/k8s-prow/generic-autobumper:v20220819-de76c58889
      command:
      - generic-autobumper
      args:
      - --config=config/prow/autobump-config/prow-job-autobump-config.yaml
      - --labels-override=skip-review # This label is used by tide for identifying trusted PR
      volumeMounts:
      - name: github
        mountPath: /etc/github-token
        readOnly: true
    volumes:
    - name: github
      secret:
        secretName: k8s-infra-ci-robot-github-token
  annotations:
    testgrid-dashboards: sig-testing-prow
    testgrid-tab-name: autobump-prowjobs-for-auto-deploy
    testgrid-alert-email: k8s-infra-oncall@google.com
    testgrid-num-failures-to-alert: '2' # This could fail when it runs right in the middle of prow push, tolerate it once
    description: runs autobumper to create/update a PR that bumps prowjob images to latest published version with label 'skip-review'
