presubmits:
  kubernetes-sigs/bom:
  - name: pull-bom-test
    always_run: true
    decorate: true
    path_alias: "sigs.k8s.io/bom"
    spec:
      containers:
      - image: gcr.io/k8s-staging-releng/releng-ci:latest-go1.18-bullseye
        imagePullPolicy: Always
        command:
        - go
        args:
        - run
        - mage.go
        - Test
    annotations:
      testgrid-dashboards: sig-release-releng-presubmits
      testgrid-tab-name: bom-test
      testgrid-alert-email: release-managers+alerts@kubernetes.io
      testgrid-num-columns-recent: '30'
  - name: pull-bom-verify
    always_run: true
    decorate: true
    path_alias: "sigs.k8s.io/bom"
    spec:
      containers:
      - image: gcr.io/k8s-staging-releng/releng-ci:latest-go1.18-bullseye
        imagePullPolicy: Always
        command:
        - go
        args:
        - run
        - mage.go
        - Verify
    annotations:
      testgrid-dashboards: sig-release-releng-presubmits
      testgrid-tab-name: bom-verify
      testgrid-alert-email: release-managers+alerts@kubernetes.io
      testgrid-num-columns-recent: '30'
