dashboard_groups:
- name: sig-node
  dashboard_names:
    - sig-node-release-blocking # This is a replica of sig-node jobs that are release blocking.
    - sig-node-kubelet
    - sig-node-containerd
    - sig-node-cri-o
    - sig-node-cos
    - sig-node-presubmits
    # These dashboards are for out-of-tree SIG Node projects
    - sig-node-cadvisor
    - sig-node-cri-tools
    - sig-node-node-feature-discovery
    - sig-node-kernel-module-management
    - sig-node-node-problem-detector
    - sig-node-security-profiles-operator

dashboards:
- name: sig-node-release-blocking # Tabs included in this group are defined in the jobs that are included.

- name: sig-node-cadvisor
- name: sig-node-kubelet
- name: sig-node-containerd
  dashboard_tab:
    - name: pull-node-e2e
      test_group_name: pull-kubernetes-node-e2e-containerd
      base_options: width=10
    - name: pull-e2e-gci
      test_group_name: pull-kubernetes-e2e-containerd-gce
      base_options: width=10
    - name: pull-e2e-podutil
      test_group_name: pull-kubernetes-node-e2e-podutil
      base_options: width=10

- name: sig-node-cri-o
  dashboard_tab:
    - name: crio-e2e-fedora
      test_group_name: test_pull_request_crio_e2e_fedora
      open_test_template:
        url: https://gcsweb-ci.svc.ci.openshift.org/gcs/<gcs_prefix>/<changelist>.txt
      results_url_template:
        url: https://gcsweb-ci.svc.ci.openshift.org/gcs/<gcs_prefix>
      base_options: width=10
    - name: crio-e2e-rhel
      test_group_name: test_pull_request_crio_e2e_rhel
      open_test_template:
        url: https://gcsweb-ci.svc.ci.openshift.org/gcs/<gcs_prefix>/<changelist>.txt
      results_url_template:
        url: https://gcsweb-ci.svc.ci.openshift.org/gcs/<gcs_prefix>
      base_options: width=10

- name: sig-node-cri-tools
- name: sig-node-node-feature-discovery
- name: sig-node-kernel-module-management

- name: sig-node-node-problem-detector

- name: sig-node-security-profiles-operator
  dashboard_tab:
  - name: build
    test_group_name: pull-security-profiles-operator-build
    base_options: width=10
  - name: build-image
    test_group_name: pull-security-profiles-operator-build-image
    base_options: width=10
  - name: verify
    test_group_name: pull-security-profiles-operator-verify
    base_options: width=10
  - name: test-unit
    test_group_name: pull-security-profiles-operator-test-unit
    base_options: width=10
  - name: test-e2e
    test_group_name: pull-security-profiles-operator-test-e2e
    base_options: width=10
  - name: push-image
    test_group_name: post-security-profiles-operator-push-image
    base_options: width=10

- name: sig-node-cos
- name: sig-node-presubmits
