dashboard_groups:
- name: sig-windows
  dashboard_names:
    - sig-windows-signal
    - sig-windows-1.22-release
    - sig-windows-1.23-release
    - sig-windows-1.24-release
    - sig-windows-1.25-release
    - sig-windows-master-release
    - sig-windows-presubmit
    - sig-windows-gce
    - sig-windows-networking
    - sig-windows-containerd-runtime-signal
    - sig-windows-push-images
    - sig-windows-soak-tests

dashboards:
- name: sig-windows-signal
- name: sig-windows-1.22-release
- name: sig-windows-1.23-release
- name: sig-windows-1.24-release
- name: sig-windows-1.25-release
- name: sig-windows-master-release
- name: sig-windows-presubmit
- name: sig-windows-gce
- name: sig-windows-push-images
- name: sig-windows-soak-tests
  dashboard_tab:
    - name: soak-tests-capz-windows
      description: Windows 2019 SOAK tests
      test_group_name: sig-windows-soak-tests
- name: sig-windows-networking
  dashboard_tab:
  - name: ltsc2019-docker-flannel-winbridge-stable-dsr-disabled
    description: Runs Windows (LTSC 2019 with Docker) E2E tests on stable branch K8s clusters (with WinDSR disabled) and latest Flannel CNI release in l2bridge network mode.
    test_group_name: k8s-e2e-ltsc2019-docker-flannel-winbridge-stable-dsr-disabled
  - name: ltsc2019-docker-flannel-winoverlay-stable-dsr-disabled
    description: Runs Windows (LTSC 2019 with Docker) E2E tests on stable branch K8s clusters (with WinDSR disabled) and latest Flannel CNI release in overlay network mode.
    test_group_name: k8s-e2e-ltsc2019-docker-flannel-winoverlay-stable-dsr-disabled
  - name: ltsc2019-docker-flannel-winbridge-stable
    description: Runs Windows (LTSC 2019 with Docker) E2E tests on stable branch K8s clusters and latest Flannel CNI release in l2bridge network mode.
    test_group_name: k8s-e2e-ltsc2019-docker-flannel-winbridge-stable
  - name: ltsc2019-docker-flannel-winoverlay-stable
    description: Runs Windows (LTSC 2019 with Docker) E2E tests on stable branch K8s clusters and latest Flannel CNI release in overlay network mode.
    test_group_name: k8s-e2e-ltsc2019-docker-flannel-winoverlay-stable
  - name: ltsc2019-containerd-flannel-sdnbridge-master
    description: Runs Windows (LTSC 2019 with Containerd) E2E tests on master branch K8s clusters and latest Flannel CNI release in l2bridge network mode.
    test_group_name: k8s-e2e-ltsc2019-containerd-flannel-sdnbridge-master
  - name: ltsc2019-containerd-flannel-sdnoverlay-master
    description: Runs Windows (LTSC 2019 with Containerd) E2E tests on master branch K8s clusters and latest Flannel CNI release in overlay network mode.
    test_group_name: k8s-e2e-ltsc2019-containerd-flannel-sdnoverlay-master
  - name: ltsc2019-containerd-flannel-sdnbridge-stable
    description: Runs Windows (LTSC 2019 with Containerd) E2E tests on stable branch K8s clusters and latest Flannel CNI release in l2bridge network mode.
    test_group_name: k8s-e2e-ltsc2019-containerd-flannel-sdnbridge-stable
  - name: ltsc2019-containerd-flannel-sdnoverlay-stable
    description: Runs Windows (LTSC 2019 with Containerd) E2E tests on stable branch K8s clusters and latest Flannel CNI release in overlay network mode.
    test_group_name: k8s-e2e-ltsc2019-containerd-flannel-sdnoverlay-stable
  - name: ltsc2022-containerd-flannel-sdnbridge-stable
    description: Runs Windows (LTSC 2022 with Containerd) E2E tests on stable branch K8s clusters and latest Flannel CNI release in l2bridge network mode.
    test_group_name: k8s-e2e-ltsc2022-containerd-flannel-sdnbridge-stable
  - name: ltsc2022-containerd-flannel-sdnoverlay-stable
    description: Runs Windows (LTSC 2022 with Containerd) E2E tests on stable branch K8s clusters and latest Flannel CNI release in overlay network mode.
    test_group_name: k8s-e2e-ltsc2022-containerd-flannel-sdnoverlay-stable
- name: sig-windows-containerd-runtime-signal
  dashboard_tab:
  - name: win-2019-containerd-master-integration
    description: Runs containerd integration & cri-integration tests on Windows (LTSC 2019)
    test_group_name: integration-containerd-windows-ltsc2019
  - name: win-2022-containerd-master-integration
    description: Runs containerd integration & cri-integration tests on Windows (LTSC 2022)
    test_group_name: integration-containerd-windows-ltsc2022


test_groups:
# Flannel CNI on Windows test groups
- name: k8s-e2e-ltsc2019-docker-flannel-winbridge-stable-dsr-disabled
  gcs_prefix: k8s-ovn/logs/k8s-e2e-ltsc2019-docker-flannel-winbridge-stable-dsr-disabled
- name: k8s-e2e-ltsc2019-docker-flannel-winoverlay-stable-dsr-disabled
  gcs_prefix: k8s-ovn/logs/k8s-e2e-ltsc2019-docker-flannel-winoverlay-stable-dsr-disabled
- name: k8s-e2e-ltsc2019-docker-flannel-winbridge-stable
  gcs_prefix: k8s-ovn/logs/k8s-e2e-ltsc2019-docker-flannel-winbridge-stable
- name: k8s-e2e-ltsc2019-docker-flannel-winoverlay-stable
  gcs_prefix: k8s-ovn/logs/k8s-e2e-ltsc2019-docker-flannel-winoverlay-stable
- name: k8s-e2e-ltsc2019-containerd-flannel-sdnbridge-master
  gcs_prefix: k8s-ovn/logs/k8s-e2e-ltsc2019-containerd-flannel-sdnbridge-master
- name: k8s-e2e-ltsc2019-containerd-flannel-sdnoverlay-master
  gcs_prefix: k8s-ovn/logs/k8s-e2e-ltsc2019-containerd-flannel-sdnoverlay-master
- name: k8s-e2e-ltsc2019-containerd-flannel-sdnbridge-stable
  gcs_prefix: k8s-ovn/logs/k8s-e2e-ltsc2019-containerd-flannel-sdnbridge-stable
- name: k8s-e2e-ltsc2019-containerd-flannel-sdnoverlay-stable
  gcs_prefix: k8s-ovn/logs/k8s-e2e-ltsc2019-containerd-flannel-sdnoverlay-stable
- name: k8s-e2e-ltsc2022-containerd-flannel-sdnbridge-stable
  gcs_prefix: k8s-ovn/logs/k8s-e2e-ltsc2022-containerd-flannel-sdnbridge-stable
- name: k8s-e2e-ltsc2022-containerd-flannel-sdnoverlay-stable
  gcs_prefix: k8s-ovn/logs/k8s-e2e-ltsc2022-containerd-flannel-sdnoverlay-stable
# Containerd Runtime integration test groups
- name: integration-containerd-windows-ltsc2019
  gcs_prefix: containerd-integration/logs/windows-ltsc2019
  disable_prowjob_analysis: true
- name: integration-containerd-windows-ltsc2022
  gcs_prefix: containerd-integration/logs/windows-ltsc2022
  disable_prowjob_analysis: true
# Windows SOAK tests
- name: sig-windows-soak-tests
  gcs_prefix: sig-windows-soak-tests/logs/windows-capz
