periodics:
- name: ci-crio-cgroupv1-node-e2e-conformance
  interval: 1h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
      args:
      - --root=/go/src
      - --repo=k8s.io/kubernetes
      - "--timeout=240"
      - --scenario=kubernetes_e2e
      - -- # end bootstrap args, scenario args below
      - --deployment=node
      - --env=KUBE_SSH_USER=core
      - --gcp-project-type=node-e2e-project
      - --gcp-zone=us-west1-b
      - '--node-test-args=--container-runtime-endpoint=unix:///var/run/crio/crio.sock --container-runtime-process-name=/usr/local/bin/crio --container-runtime-pid-file= --kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/crio.service --kubelet-cgroups=/system.slice/kubelet.service" --extra-log="{\"name\": \"crio.log\", \"journalctl\": [\"-u\", \"crio\"]}"'
      - --node-tests=true
      - --provider=gce
      - --test_args=--nodes=8 --focus="\[NodeConformance\]" --skip="\[Flaky\]|\[Slow\]|\[Serial\]"
      - --timeout=180m
      - --node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/crio/latest/image-config-cgrpv1.yaml
      env:
      - name: GOPATH
        value: /go
  annotations:
    testgrid-dashboards: sig-node-cri-o, sig-release-master-informing
    testgrid-tab-name: ci-crio-cgroupv1-node-e2e-conformance
    testgrid-alert-email: kubernetes-sig-node-test-failures@googlegroups.com
    description: "OWNER: sig-node; runs NodeConformance e2e tests with crio master and cgroup v1"
# TODO (https://github.com/kubernetes/test-infra/issues/26127) consider restoring once we will figure out the right set of alpha features. The tag NodeAlphaFeature is not being used any longer
# - name: ci-crio-cgroupv1-node-e2e-alpha
#   interval: 1h
#   labels:
#     preset-service-account: "true"
#     preset-k8s-ssh: "true"
#   spec:
#     containers:
#     - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
#       args:
#       - --root=/go/src
#       - --repo=k8s.io/kubernetes
#       - "--timeout=90"
#       - --scenario=kubernetes_e2e
#       - -- # end bootstrap args, scenario args below
#       - --deployment=node
#       - --env=KUBE_SSH_USER=core
#       - --gcp-project-type=node-e2e-project
#       - --gcp-zone=us-west1-b
#       - '--node-test-args=--feature-gates=AllAlpha=true,RotateKubeletServerCertificate=false,InTreePluginGCEUnregister=false --container-runtime-endpoint=unix:///var/run/crio/crio.sock --container-runtime-process-name=/usr/local/bin/crio --container-runtime-pid-file= --kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/crio.service --kubelet-cgroups=/system.slice/kubelet.service" --extra-log="{\"name\": \"crio.log\", \"journalctl\": [\"-u\", \"crio\"]}"'
#       - --node-tests=true
#       - --provider=gce
#       - --test_args=--nodes=8 --focus="\[NodeAlphaFeature:.+\]|\[NodeAlphaFeature\]" --skip="\[Flaky\]|\[Serial\]"
#       - --runtime-config=api/all=true
#       - --timeout=65m
#       - --node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/crio/latest/image-config-cgrpv1.yaml
#       env:
#       - name: GOPATH
#         value: /go
#   annotations:
#     testgrid-dashboards: sig-node-cri-o
#     testgrid-tab-name: ci-crio-cgroupv1-node-e2e-alpha
#     testgrid-alert-email: kubernetes-sig-node-test-failures@googlegroups.com
#     description: "OWNER: sig-node; runs NodeConformance and alpha e2e tests with crio master and cgroup v1"
- name: ci-crio-cgroupv1-node-e2e-features
  interval: 1h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
      args:
      - --root=/go/src
      - --repo=k8s.io/kubernetes
      - "--timeout=240"
      - --scenario=kubernetes_e2e
      - -- # end bootstrap args, scenario args below
      - --deployment=node
      - --env=KUBE_SSH_USER=core
      - --gcp-project-type=node-e2e-project
      - --gcp-zone=us-west1-b
      - '--node-test-args=--container-runtime-endpoint=unix:///var/run/crio/crio.sock --container-runtime-process-name=/usr/local/bin/crio --container-runtime-pid-file= --kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/crio.service --kubelet-cgroups=/system.slice/kubelet.service" --extra-log="{\"name\": \"crio.log\", \"journalctl\": [\"-u\", \"crio\"]}"'
      - --node-tests=true
      - --provider=gce
      - --test_args=--nodes=8 --focus="\[NodeFeature:.+\]|\[NodeFeature\]" --skip="\[Flaky\]|\[Slow\]|\[Serial\]"
      - --timeout=180m
      - --node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/crio/latest/image-config-cgrpv1.yaml
      env:
      - name: GOPATH
        value: /go
  annotations:
    testgrid-dashboards: sig-node-cri-o
    testgrid-tab-name: ci-crio-cgroupv1-node-e2e-features
    testgrid-alert-email: kubernetes-sig-node-test-failures@googlegroups.com
    description: "OWNER: sig-node; runs NodeFeatures e2e tests with crio master and cgroup v1"
- name: ci-crio-cgroupv1-node-e2e-flaky
  interval: 2h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
      args:
      - --root=/go/src
      - --repo=k8s.io/kubernetes
      - "--timeout=90"
      - --scenario=kubernetes_e2e
      - -- # end bootstrap args, scenario args below
      - --deployment=node
      - --env=KUBE_SSH_USER=core
      - --gcp-project-type=node-e2e-project
      - --gcp-zone=us-west1-b
      - '--node-test-args=--container-runtime-endpoint=unix:///var/run/crio/crio.sock --container-runtime-process-name=/usr/local/bin/crio --container-runtime-pid-file= --kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/crio.service --kubelet-cgroups=/system.slice/kubelet.service" --extra-log="{\"name\": \"crio.log\", \"journalctl\": [\"-u\", \"crio\"]}"'
      - --node-tests=true
      - --provider=gce
      - --test_args=--nodes=1 --focus="\[Flaky\]"
      - --timeout=60m
      - --node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/crio/latest/image-config-cgrpv1.yaml
      env:
      - name: GOPATH
        value: /go
  annotations:
    testgrid-dashboards: sig-node-cri-o
    testgrid-tab-name: ci-crio-cgroupv1-node-e2e-flaky
    testgrid-alert-email: kubernetes-sig-node-test-failures@googlegroups.com
    description: "OWNER: sig-node; runs NodeFeatures e2e tests with crio master and cgroup v1"
- name: ci-crio-cgroupv1-node-e2e-unlabelled
  interval: 12h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
      args:
      - --root=/go/src
      - --repo=k8s.io/kubernetes
      - "--timeout=400"
      - --scenario=kubernetes_e2e
      - -- # end bootstrap args, scenario args below
      - --deployment=node
      - --env=KUBE_SSH_USER=core
      - --gcp-project-type=node-e2e-project
      - --gcp-zone=us-west1-b
      - '--node-test-args=--container-runtime-endpoint=unix:///var/run/crio/crio.sock --container-runtime-process-name=/usr/local/bin/crio --container-runtime-pid-file= --kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/crio.service --kubelet-cgroups=/system.slice/kubelet.service" --extra-log="{\"name\": \"crio.log\", \"journalctl\": [\"-u\", \"crio\"]}"'
      - --node-tests=true
      - --provider=gce
      - --test_args=--nodes=1 --skip="\[Flaky\]|\[NodeConformance\]|\[Conformance\]|\[Serial\]|\[NodeFeature:.+\]|\[NodeFeature\]|\[Feature:.+\]|\[Feature\]|\[NodeSpecialFeature:.+\]|\[NodeSpecialFeature\]|\[NodeAlphaFeature:.+\]|\[NodeAlphaFeature\]|\[Legacy:.+\]|\[Benchmark\]|\[Feature:SCTPConnectivity\]"
      - --timeout=300m
      - --node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/crio/latest/image-config-cgrpv1.yaml
      env:
      - name: GOPATH
        value: /go
  annotations:
    testgrid-dashboards: sig-node-cri-o
    testgrid-tab-name: ci-crio-cgroupv1-node-e2e-unlabelled
    testgrid-alert-email: kubernetes-sig-node-test-failures@googlegroups.com
    description: "Contains all uncategorized tests, these are tests which are not marked with a [Node] tag. All node tests should be marked with [NodeFeature] or [NodeSpecialFeature] or [NodeAlphaFeature] or [NodeConformance] classification. Also skipped are [Flaky], [Benchmark], [Legacy]."
- name: ci-crio-cgroupv1-node-e2e-eviction
  interval: 4h30m
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
      args:
      - --root=/go/src
      - --repo=k8s.io/kubernetes
      - "--timeout=320"
      - --scenario=kubernetes_e2e
      - -- # end bootstrap args, scenario args below
      - --deployment=node
      - --env=KUBE_SSH_USER=core
      - --gcp-project-type=node-e2e-project
      - --gcp-zone=us-west1-b
      - '--node-test-args=--feature-gates=LocalStorageCapacityIsolation=true --container-runtime-endpoint=unix:///var/run/crio/crio.sock --container-runtime-process-name=/usr/local/bin/crio --container-runtime-pid-file= --kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/crio.service --kubelet-cgroups=/system.slice/kubelet.service" --extra-log="{\"name\": \"crio.log\", \"journalctl\": [\"-u\", \"crio\"]}"'
      - --node-tests=true
      - --provider=gce
      - --test_args=--nodes=1 --focus="\[NodeFeature:Eviction\]"
      - --timeout=300m
      - --node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/crio/latest/image-config-cgrpv1.yaml
      env:
      - name: GOPATH
        value: /go
  annotations:
    testgrid-dashboards: sig-node-cri-o
    testgrid-tab-name: ci-crio-cgroupv1-node-e2e-eviction
    testgrid-alert-email: kubernetes-sig-node-test-failures@googlegroups.com
    description: "OWNER: sig-node; runs Eviction e2e tests with crio master and cgroup v1"
- name: ci-crio-cgroupv2-node-e2e-conformance
  interval: 1h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
      args:
      - --root=/go/src
      - --repo=k8s.io/kubernetes
      - "--timeout=240"
      - --scenario=kubernetes_e2e
      - -- # end bootstrap args, scenario args below
      - --deployment=node
      - --env=KUBE_SSH_USER=core
      - --gcp-project-type=node-e2e-project
      - --gcp-zone=us-west1-b
      - '--node-test-args=--container-runtime-endpoint=unix:///var/run/crio/crio.sock --container-runtime-process-name=/usr/local/bin/crio --container-runtime-pid-file= --kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/crio.service --kubelet-cgroups=/system.slice/kubelet.service" --extra-log="{\"name\": \"crio.log\", \"journalctl\": [\"-u\", \"crio\"]}"'
      - --node-tests=true
      - --provider=gce
      - --test_args=--nodes=8 --focus="\[NodeConformance\]" --skip="\[Flaky\]|\[Slow\]|\[Serial\]"
      - --timeout=180m
      - --node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/crio/latest/image-config-cgrpv2.yaml
      env:
      - name: GOPATH
        value: /go
  annotations:
    testgrid-dashboards: sig-node-cri-o
    testgrid-tab-name: ci-crio-cgroupv2-node-e2e-conformance
    testgrid-alert-email: kubernetes-sig-node-test-failures@googlegroups.com
    description: "OWNER: sig-node; runs NodeConformance e2e tests with crio master and cgroup v2"
- name: ci-crio-cgroupv1-node-e2e-resource-managers
  interval: 4h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        args:
          - --repo=k8s.io/kubernetes=master
          - --timeout=120
          - --root=/go/src
          - --scenario=kubernetes_e2e
          - -- # end bootstrap args, scenario args below
          - --deployment=node
          - --env=KUBE_SSH_USER=core
          - --gcp-project-type=node-e2e-project
          - --gcp-zone=us-west1-b
          - '--node-test-args=--feature-gates=LocalStorageCapacityIsolation=true --container-runtime-endpoint=unix:///var/run/crio/crio.sock --container-runtime-process-name=/usr/local/bin/crio --container-runtime-pid-file= --kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/crio.service --kubelet-cgroups=/system.slice/kubelet.service" --extra-log="{\"name\": \"crio.log\", \"journalctl\": [\"-u\", \"crio\"]}"'
          - --node-tests=true
          - --provider=gce
          - --test_args=--nodes=1 --focus="\[Feature:CPUManager\]|\[Feature:MemoryManager\]|\[Feature:TopologyManager\]"
          - --timeout=90m
          - --node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/crio/latest/image-config-cgrpv1-resource-managers.yaml
        env:
          - name: GOPATH
            value: /go
  annotations:
    testgrid-dashboards: sig-node-cri-o
    testgrid-tab-name: ci-crio-cgroupv1-node-e2e-resource-managers
    testgrid-alert-email: kubernetes-sig-node-test-failures@googlegroups.com
    description: "Executes CPU, Memory and Topology manager e2e tests"
- name: ci-crio-cgroupv1-node-e2e-hugepages
  interval: 4h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        args:
          - --repo=k8s.io/kubernetes=master
          - --timeout=120
          - --root=/go/src
          - --scenario=kubernetes_e2e
          - -- # end bootstrap args, scenario args below
          - --deployment=node
          - --env=KUBE_SSH_USER=core
          - --gcp-project-type=node-e2e-project
          - --gcp-zone=us-west1-b
          - '--node-test-args=--feature-gates=LocalStorageCapacityIsolation=true --container-runtime-endpoint=unix:///var/run/crio/crio.sock --container-runtime-process-name=/usr/local/bin/crio --container-runtime-pid-file= --kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/crio.service --kubelet-cgroups=/system.slice/kubelet.service" --extra-log="{\"name\": \"crio.log\", \"journalctl\": [\"-u\", \"crio\"]}"'
          - --node-tests=true
          - --provider=gce
          - --test_args=--nodes=1 --focus="\[Feature:HugePages\]"
          - --timeout=90m
          - --node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/crio/latest/image-config-cgrpv1-hugepages.yaml
        env:
          - name: GOPATH
            value: /go
  annotations:
    testgrid-dashboards: sig-node-cri-o
    testgrid-tab-name: ci-crio-cgroupv1-node-e2e-hugepages
    testgrid-alert-email: kubernetes-sig-node-test-failures@googlegroups.com
    description: "Executes hugepages e2e tests"
