periodics:
- name: periodic-cluster-api-provider-aws-e2e-release-0-7
  decorate: true
  decoration_config:
    timeout: 5h
  interval: 6h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-aws
    base_ref: release-0.7
    path_alias: "sigs.k8s.io/cluster-api-provider-aws"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220727-f055b40439-1.21
      command:
        - "runner.sh"
        - "./scripts/ci-e2e.sh"
      env:
      - name: BOSKOS_HOST
        value: "boskos.test-pods.svc.cluster.local"
      - name: AWS_REGION
        value: "us-west-2"
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 2
          memory: "9Gi"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-aws
    testgrid-tab-name: periodic-e2e-release-0-7
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-aws-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "2"
- name: periodic-cluster-api-provider-aws-capi-e2e-release-0-7
  decorate: true
  decoration_config:
    timeout: 5h
  interval: 24h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api-provider-aws
      base_ref: release-0.7
      path_alias: "sigs.k8s.io/cluster-api-provider-aws"
  spec:
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220727-f055b40439-1.21
        command:
          - "runner.sh"
          - "./scripts/ci-e2e.sh"
        env:
          - name: BOSKOS_HOST
            value: "boskos.test-pods.svc.cluster.local"
          - name: AWS_REGION
            value: "us-west-2"
          - name: E2E_FOCUS
            value: "\\[Cluster API Framework\\]"
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 2
            memory: "9Gi"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-aws
    testgrid-tab-name: periodic-capi-e2e-release-0-7
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-aws-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "2"
- name: periodic-cluster-api-provider-aws-e2e-conformance-release-0-7
  decorate: true
  decoration_config:
    timeout: 5h
  interval: 12h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api-provider-aws
      base_ref: release-0.7
      path_alias: "sigs.k8s.io/cluster-api-provider-aws"
  spec:
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220727-f055b40439-1.21
        command:
          - "runner.sh"
          - "./scripts/ci-conformance.sh"
        env:
          - name: BOSKOS_HOST
            value: "boskos.test-pods.svc.cluster.local"
          - name: AWS_REGION
            value: "us-west-2"
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 2
            memory: "9Gi"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-aws
    testgrid-tab-name: periodic-conformance-release-0-7
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-aws-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "2"
