periodics:
- name: periodic-cluster-api-provider-aws-e2e-release-1-5
  decorate: true
  decoration_config:
    timeout: 5h
  interval: 12h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-aws
    base_ref: release-1.5
    path_alias: "sigs.k8s.io/cluster-api-provider-aws"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
      command:
        - "runner.sh"
        - "./scripts/ci-e2e.sh"
      env:
      - name: BOSKOS_HOST
        value: "boskos.test-pods.svc.cluster.local"
      - name: AWS_REGION
        value: "us-west-2"
      # Parallelize tests
      - name: GINKGO_ARGS
        value: "-nodes 20 -skip='\\[ClusterClass\\]'"
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 2
          memory: "9Gi"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-aws-1.5
    testgrid-tab-name: periodic-e2e-release-1-5
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-aws-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "2"
- name: periodic-cluster-api-provider-aws-eks-e2e-release-1-5
  decorate: true
  decoration_config:
    timeout: 5h
  interval: 12h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-aws
    base_ref: release-1.5
    path_alias: "sigs.k8s.io/cluster-api-provider-aws"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
      command:
        - "runner.sh"
        - "./scripts/ci-e2e-eks.sh"
      env:
      - name: BOSKOS_HOST
        value: "boskos.test-pods.svc.cluster.local"
      - name: AWS_REGION
        value: "us-west-2"
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 2
          memory: "9Gi"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-aws-1.5
    testgrid-tab-name: periodic-eks-e2e-release-1-5
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-aws-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "2"
- name: periodic-cluster-api-provider-aws-e2e-conformance-release-1-5
  decorate: true
  decoration_config:
    timeout: 5h
  interval: 12h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api-provider-aws
      base_ref: release-1.5
      path_alias: "sigs.k8s.io/cluster-api-provider-aws"
  spec:
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
        command:
          - "runner.sh"
          - "./scripts/ci-conformance.sh"
        env:
          - name: BOSKOS_HOST
            value: "boskos.test-pods.svc.cluster.local"
          - name: AWS_REGION
            value: "us-west-2"
          # Parallelize tests
          - name: GINKGO_ARGS
            value: "-nodes 20"
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 2
            memory: "9Gi"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-aws-1.5
    testgrid-tab-name: periodic-conformance-release-1-5
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-aws-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "2"
- name: periodic-cluster-api-provider-aws-e2e-conformance-with-k8s-ci-artifacts-release-1-5
  max_concurrency: 1
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 5h
  interval: 12h
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api-provider-aws
      base_ref: release-1.5
      path_alias: "sigs.k8s.io/cluster-api-provider-aws"
    - org: kubernetes-sigs
      repo: image-builder
      base_ref: master
      path_alias: "sigs.k8s.io/image-builder"
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
  spec:
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
        env:
          - name: BOSKOS_HOST
            value: "boskos.test-pods.svc.cluster.local"
          - name: AWS_REGION
            value: "us-west-2"
          - name: E2E_ARGS
            value: "-kubetest.use-ci-artifacts"
          # Parallelize tests
          - name: GINKGO_ARGS
            value: "-nodes 20"
        command:
          - "runner.sh"
          - "./scripts/ci-conformance.sh"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            # these are both a bit below peak usage during build
            # this is mostly for building kubernetes
            memory: "9Gi"
            cpu: 2
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-aws-1.5
    testgrid-tab-name: periodic-conformance-release-1-5-k8s-main
    testgrid-num-columns-recent: '20'
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-aws-alerts@kubernetes.io
