presubmits:
  kubernetes-sigs/release-sdk:
  - name: pull-release-sdk-test
    always_run: true
    decorate: true
    path_alias: "sigs.k8s.io/release-sdk"
    spec:
      containers:
      - image: gcr.io/k8s-staging-releng/releng-ci:latest-go1.18-bullseye
        imagePullPolicy: Always
        command:
        - go
        args:
        - run
        - mage.go
        - Test
    annotations:
      testgrid-dashboards: sig-release-releng-presubmits
      testgrid-tab-name: release-sdk-test
      testgrid-alert-email: release-managers+alerts@kubernetes.io
      testgrid-num-columns-recent: '30'
  - name: pull-release-sdk-integration-test
    always_run: true
    decorate: true
    path_alias: "sigs.k8s.io/release-sdk"
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-releng/k8s-ci-builder:latest-default
        imagePullPolicy: Always
        command:
        - wrapper.sh
        args:
        - go
        - run
        - mage.go
        - IntegrationTest
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-release-releng-presubmits
      testgrid-tab-name: release-sdk-integration-test
      testgrid-alert-email: release-managers+alerts@kubernetes.io
      testgrid-num-columns-recent: '30'
  - name: pull-release-sdk-verify
    always_run: true
    decorate: true
    path_alias: "sigs.k8s.io/release-sdk"
    spec:
      containers:
      - image: gcr.io/k8s-staging-releng/releng-ci:latest-go1.18-bullseye
        imagePullPolicy: Always
        command:
        - go
        args:
        - run
        - mage.go
        - Verify
    annotations:
      testgrid-dashboards: sig-release-releng-presubmits
      testgrid-tab-name: release-sdk-verify
      testgrid-alert-email: release-managers+alerts@kubernetes.io
      testgrid-num-columns-recent: '30'
