periodics:
- interval: 12h
  cluster: k8s-infra-prow-build
  # This combines tests from ci-kubernetes-kind-conformance and sig-storage
  # and runs them with JSON output in all components which support that.
  name: ci-kubernetes-kind-e2e-json-logging
  annotations:
    testgrid-dashboards: sig-instrumentation-tests, sig-testing-kind
    testgrid-tab-name: kind-json-logging-master
    description: Conformance and storage tests with JSON logging enabled using sigs.k8s.io/kind
    # TODO: anyone else?
    testgrid-alert-email: bentheelder@google.com,siarkowicz@google.com,patrick.ohly@intel.com
    testgrid-num-columns-recent: '6'
    fork-per-release: "true"
    fork-per-release-periodic-interval: 1h 2h 6h 24h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  decorate: true
  decoration_config:
    timeout: 150m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/krte:v20220804-9dd62ce78a-master
      command:
      - wrapper.sh
      - bash
      - -c
      - curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && e2e-k8s.sh
      env:
      # Options from https://github.com/kubernetes-sigs/kind/blob/d1eecc46e30cac9d35cd32dc52677ef75ec22e18/hack/ci/e2e-k8s.sh#L79-L83
      - name: CLUSTER_LOG_FORMAT
        value: json
      - name: KIND_CLUSTER_LOG_LEVEL
        # Default is 4, but we want to exercise more log calls and get more output.
        value: "10"
      # don't retry conformance tests
      - name: GINKGO_TOLERATE_FLAKES
        value: "n"
      - name: FOCUS
        value: \[Conformance\]|\[Driver:.csi-hostpath\]
      # TODO(bentheelder): reduce the skip list further
      # NOTE: this skip list is from the standard periodic kind job, just to ensure
      # we don't accidentally select any of these
      - name: SKIP
        value: \[Slow\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|PodSecurityPolicy|LoadBalancer|load.balancer|In-tree.Volumes.\[Driver:.nfs\]|PersistentVolumes.NFS|Network.should.set.TCP.CLOSE_WAIT.timeout|Simple.pod.should.support.exec.through.an.HTTP.proxy|subPath.should.support.existing|should.provide.basic.identity
      - name: PARALLEL
        value: "true"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        limits:
          memory: 9Gi
          cpu: 7
        requests:
          # these are both a bit below peak usage during build
          # this is mostly for building kubernetes
          memory: 9Gi
          cpu: 7
