presubmits:
  kubernetes/k8s.io:
  - name: pull-k8sio-groups-test
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: sig-k8s-infra-groups
    decorate: true
    path_alias: k8s.io/k8s.io
    run_if_changed: "^groups/"
    branches:
    - ^main$
    spec:
      containers:
      - image: gcr.io/k8s-staging-infra-tools/k8s-infra:latest
        command:
        - make
        args:
        - -C
        - ./groups
        - test
        env:
        - name: GO111MODULE
          value: "on"
  - name: pull-k8sio-terraform-org-kubernetes-io
    annotations:
      description: verify terraform files for kubernetes.io Organization
      testgrid-create-test-group: 'true'
      testgrid-dashboards: sig-k8s-infra-k8sio
      testgrid-tab-name: pull-k8sio-terraform-kubernetes-io
      testgrid-alert-email: ameukam@gmail.com,spiffxp@gmail.com,spiffxp@google.com
      testgrid-num-failures-to-alert: '1'
    decorate: true
    max_concurrency: 1
    cluster: k8s-infra-prow-build
    path_alias: k8s.io/k8s.io
    run_if_changed: 'infra\/gcp\/terraform\/(modules|k8s-infra-kubernetes-io)\/.*.tf'
    branches:
    - ^main$
    spec:
      containers:
      - image: gcr.io/k8s-staging-infra-tools/k8s-infra:latest
        command:
        - hack/verify-terraform.sh
        args:
        - infra/gcp/terraform/k8s-infra-kubernetes-io
        resources:
          limits:
            cpu: 1
            memory: "512Mi"
          requests:
            cpu: 1
            memory: "512Mi"
  - name: pull-k8sio-terraform-kubernetes-public
    annotations:
      description: verify terraform files for GKE cluster aaa
      testgrid-create-test-group: 'true'
      testgrid-dashboards: sig-k8s-infra-k8sio
      testgrid-tab-name: pull-k8sio-terraform-kubernetes-public
      testgrid-alert-email: ameukam@gmail.com,spiffxp@gmail.com,spiffxp@google.com
      testgrid-num-failures-to-alert: '1'
    decorate: true
    max_concurrency: 1
    cluster: k8s-infra-prow-build
    path_alias: k8s.io/k8s.io
    run_if_changed: 'infra\/gcp\/terraform\/(modules|kubernetes-public)\/.*.tf'
    branches:
    - ^main$
    spec:
      containers:
      - image: gcr.io/k8s-staging-infra-tools/k8s-infra:latest
        command:
        - hack/verify-terraform.sh
        args:
        - infra/gcp/terraform/kubernetes-public
        resources:
          limits:
            cpu: 1
            memory: "512Mi"
          requests:
            cpu: 1
            memory: "512Mi"
  - name: pull-k8sio-terraform-monitoring
    annotations:
      description: verify terraform files for GCP monitoring resources
      testgrid-create-test-group: 'true'
      testgrid-dashboards: sig-k8s-infra-k8sio
      testgrid-tab-name: pull-k8sio-terraform-monitoring
      testgrid-alert-email: ameukam@gmail.com,spiffxp@gmail.com,spiffxp@google.com
      testgrid-num-failures-to-alert: '1'
    decorate: true
    max_concurrency: 1
    cluster: k8s-infra-prow-build
    path_alias: k8s.io/k8s.io
    run_if_changed: 'infra\/gcp\/terraform\/(modules|k8s-infra-monitoring)\/.*.tf'
    branches:
    - ^main$
    spec:
      containers:
      - image: gcr.io/k8s-staging-infra-tools/k8s-infra:latest
        command:
        - hack/verify-terraform.sh
        args:
        - infra/gcp/terraform/k8s-infra-monitoring
        resources:
          limits:
            cpu: 1
            memory: "512Mi"
          requests:
            cpu: 1
            memory: "512Mi"
  - name: pull-k8sio-terraform-prow-build
    annotations:
      description: verify terraform files for GKE build cluster prow-build
      testgrid-create-test-group: 'true'
      testgrid-dashboards: sig-k8s-infra-prow
      testgrid-tab-name: pull-k8sio-terraform-prow-build
      testgrid-alert-email: ameukam@gmail.com,spiffxp@gmail.com,spiffxp@google.com
      testgrid-num-failures-to-alert: '1'
    decorate: true
    max_concurrency: 1
    cluster: k8s-infra-prow-build
    path_alias: k8s.io/k8s.io
    run_if_changed: 'infra\/gcp\/terraform\/(modules|k8s-infra-prow-build)\/.*.tf'
    branches:
    - ^main$
    spec:
      containers:
      - image: gcr.io/k8s-staging-infra-tools/k8s-infra:latest
        command:
        - hack/verify-terraform.sh
        args:
        - infra/gcp/terraform/k8s-infra-prow-build
        resources:
          limits:
            cpu: 1
            memory: "512Mi"
          requests:
            cpu: 1
            memory: "512Mi"
  - name: pull-k8sio-terraform-prow-build-trusted
    annotations:
      description: verify terraform files for GKE build cluster prow-build-trusted
      testgrid-create-test-group: 'true'
      testgrid-dashboards: sig-k8s-infra-prow
      testgrid-tab-name: pull-k8sio-terraform-prow-build-trusted
      testgrid-alert-email: ameukam@gmail.com,spiffxp@gmail.com,spiffxp@google.com
      testgrid-num-failures-to-alert: '1'
    decorate: true
    max_concurrency: 1
    cluster: k8s-infra-prow-build
    path_alias: k8s.io/k8s.io
    run_if_changed: 'infra\/gcp\/terraform\/(modules|k8s-infra-prow-build-trusted)\/.*.tf'
    branches:
    - ^main$
    spec:
      containers:
      - image: gcr.io/k8s-staging-infra-tools/k8s-infra:latest
        command:
        - hack/verify-terraform.sh
        args:
        - infra/gcp/terraform/k8s-infra-prow-build-trusted
        resources:
          limits:
            cpu: 1
            memory: "512Mi"
          requests:
            cpu: 1
            memory: "512Mi"
  - name: pull-k8sio-terraform-public-pii
    annotations:
      description: verify terraform files for project k8s-infra-public-pii
      testgrid-create-test-group: 'true'
      testgrid-dashboards: sig-k8s-infra-prow
      testgrid-tab-name: pull-k8sio-terraform-public-pii
      testgrid-alert-email: ameukam@gmail.com,spiffxp@gmail.com,spiffxp@google.com
      testgrid-num-failures-to-alert: '1'
    decorate: true
    max_concurrency: 1
    cluster: k8s-infra-prow-build
    path_alias: k8s.io/k8s.io
    run_if_changed: 'infra\/gcp\/terraform\/(modules|k8s-infra-public-pii)\/.*.tf'
    branches:
    - ^main$
    spec:
      containers:
      - image: gcr.io/k8s-staging-infra-tools/k8s-infra:latest
        command:
        - hack/verify-terraform.sh
        args:
        - infra/gcp/terraform/k8s-infra-public-pii
        resources:
          limits:
            cpu: 1
            memory: "512Mi"
          requests:
            cpu: 1
            memory: "512Mi"
  - name: pull-k8sio-verify
    annotations:
      testgrid-dashboards: sig-k8s-infra-k8sio
      testgrid-tab-name: pull-k8sio-verify
    always_run: true
    decorate: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-infra-tools/k8s-infra:latest
        command:
        - ./hack/verify.sh
  - name: pull-k8sio-dns-validate-config
    run_if_changed: "^dns/"
    annotations:
      testgrid-dashboards: sig-k8s-infra-k8sio
      testgrid-tab-name: pull-k8sio-dns-validate-config
    decorate: true
    spec:
      containers:
        - image: registry.k8s.io/infra-tools/octodns:v20220319-97d14a558
          command:
            - bash
          args:
            - -c
            - "cd dns && make validate-config"
