presubmits:
  kubernetes-sigs/kernel-module-management:
  - name: pull-kernel-module-management-lint
    always_run: true
    decorate: true
    optional: true
    annotations:
      testgrid-dashboards: sig-node-kernel-module-management
      testgrid-tab-name: lint
      description: "lint the source code of kernel-module-management."
    spec:
      containers:
      - image: golang:1.18
        command:
        - ci/prow/lint
  - name: pull-kernel-module-management-unit-tests
    always_run: true
    decorate: true
    optional: true
    annotations:
      testgrid-dashboards: sig-node-kernel-module-management
      testgrid-tab-name: unit-tests
      description: "unit-tests the source code of kernel-module-management."
    spec:
      containers:
      - image: golang:1.18
        command:
        - ci/prow/unit-tests
