presubmits:
  kubernetes-sigs/node-feature-discovery:
  - name: pull-node-feature-discovery-verify
    always_run: true
    skip_branches:
    - gh-pages
    - ^release-0.6
    - ^release-0.7
    - ^release-0.8
    - ^release-0.9
    decorate: true
    annotations:
      testgrid-dashboards: sig-node-node-feature-discovery
      testgrid-tab-name: verify
      description: "Verify source code of node-feature-discovery: check formatting, lint etc."
    spec:
      containers:
      - image: golang:1.18
        command:
        - scripts/test-infra/verify.sh
  - name: pull-node-feature-discovery-verify-0-9
    always_run: true
    branches:
    - ^release-0.6
    - ^release-0.7
    - ^release-0.8
    - ^release-0.9
    decorate: true
    annotations:
      testgrid-dashboards: sig-node-node-feature-discovery
      testgrid-tab-name: verify-0.9
      description: "Verify source code of pre golang 1.17 release branches"
    spec:
      containers:
      - image: golang:1.16
        command:
        - scripts/test-infra/verify.sh
  - name: pull-node-feature-discovery-verify-docs
    always_run: true
    skip_branches:
    - gh-pages
    decorate: true
    annotations:
      testgrid-dashboards: sig-node-node-feature-discovery
      testgrid-tab-name: verify-docs
      description: "Verify documentation sources"
    spec:
      containers:
      - image: ruby:2.7
        command:
        - scripts/test-infra/mdlint.sh
  - name: pull-node-feature-discovery-build
    always_run: true
    skip_branches:
    - gh-pages
    decorate: true
    annotations:
      testgrid-dashboards: sig-node-node-feature-discovery
      testgrid-tab-name: build
      description: "Build node-feature-discovery binaries"
    spec:
      containers:
      - image: golang:1.18
        command:
        - scripts/test-infra/build.sh
  - name: pull-node-feature-discovery-build-image
    always_run: true
    skip_branches:
    - gh-pages
    decorate: true
    annotations:
      testgrid-dashboards: sig-node-node-feature-discovery
      testgrid-tab-name: build-image
      description: "Build container image of node-feature-discovery"
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        securityContext:
          privileged: true
        command:
        - runner.sh
        args:
        - scripts/test-infra/build-image.sh
  - name: pull-node-feature-discovery-build-image-cross
    always_run: true
    skip_branches:
    - gh-pages
    - ^release-0.6
    - ^release-0.7
    - ^release-0.8
    - ^release-0.9
    decorate: true
    annotations:
      testgrid-dashboards: sig-node-node-feature-discovery
      testgrid-tab-name: build-image-cross
      description: "Build multiarch container images of node-feature-discovery"
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        securityContext:
          privileged: true
        command:
        - runner.sh
        args:
        - scripts/test-infra/build-image-cross.sh
  - name: pull-node-feature-discovery-build-gh-pages
    always_run: true
    skip_branches:
    - gh-pages
    decorate: true
    annotations:
      testgrid-dashboards: sig-node-node-feature-discovery
      testgrid-tab-name: build-gh-pages
      description: "Test build of gh-pages documentation"
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        securityContext:
          privileged: true
        command:
        - runner.sh
        args:
        - scripts/test-infra/build-gh-pages.sh
