# sigs.k8s.io/etcdadm presubmits
presubmits:
  kubernetes-sigs/etcdadm:
  - name: pull-etcdadm-verify
    path_alias: "sigs.k8s.io/etcdadm"
    always_run: true
    decorate: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        command:
        - "./hack/verify-all.sh"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-etcdadm
      testgrid-tab-name: pr-verify
  - name: pull-etcdadm-test-init
    labels:
      preset-dind-enabled: "true"
    path_alias: "sigs.k8s.io/etcdadm"
    always_run: true
    decorate: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        command:
        - "runner.sh"
        - "./test/e2e/init.sh"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-etcdadm
      testgrid-tab-name: pr-test-init
