postsubmits:
  kubernetes-sigs/promo-tools:
    # TODO(releng): Rename to 'kpromo' once tools are merged
    - name: post-cip-push-image-cip
      cluster: k8s-infra-prow-build-trusted
      annotations:
        testgrid-dashboards: sig-release-releng-blocking, sig-release-master-informing, sig-release-image-pushes, sig-k8s-infra-gcb
        testgrid-alert-email: k8s-infra-alerts@kubernetes.io, release-managers+alerts@kubernetes.io
        testgrid-num-failures-to-alert: '1'
      decorate: true
      branches:
        - ^main$
      spec:
        serviceAccountName: gcb-builder
        containers:
          - image: gcr.io/k8s-staging-test-infra/image-builder:v20220428-ae431ed1aa
            command:
              - /run.sh
            args:
              - --project=k8s-staging-artifact-promoter
              - --scratch-bucket=gs://k8s-staging-artifact-promoter-gcb
              - --env-passthrough=PULL_BASE_REF
              - .
            env:
              - name: LOG_TO_STDOUT
                value: "y"
      rerun_auth_config:
        github_team_slugs:
          - org: kubernetes
            slug: release-managers
