presubmits:
  kubernetes/cloud-provider-openstack:
  - name: openstack-cloud-csi-cinder-sanity-test-release-123
    always_run: false
    run_if_changed: '^(pkg\/util\/|pkg\/csi\/cinder\/|cmd\/cinder-csi-plugin\/|tests\/sanity\/cinder\/)'
    decorate: true
    branches:
      - ^release-1.23$
    path_alias: "k8s.io/cloud-provider-openstack"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        command:
        - make
        args:
        - test-cinder-csi-sanity
    annotations:
      testgrid-dashboards: provider-openstack-openstack-csi-cinder
      testgrid-tab-name: presubmit-sanity-test-release-1.23
      description: Run cloud-provider-openstack csi sanity tests for cinder-csi-plugin

  - name: openstack-cloud-controller-manager-e2e-test-release-123
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    path_alias: "k8s.io/cloud-provider-openstack"
    always_run: false
    branches:
      - ^release-1.23$
    run_if_changed: '^(pkg\/util\/|pkg\/openstack\/|cmd\/openstack-cloud-controller-manager\/|tests\/e2e\/cloudprovider\/)'
    optional: false
    decorate: true
    decoration_config:
      timeout: 3h
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
          env:
          - name: "BOSKOS_HOST"
            value: "boskos.test-pods.svc.cluster.local"
          command:
          - "runner.sh"
          - "./tests/ci-occm-e2e.sh"
          securityContext:
            privileged: true
          resources:
            requests:
              memory: "1Gi"
              cpu: 1
    annotations:
      testgrid-dashboards: provider-openstack-openstack-cloud-controller-manager
      testgrid-tab-name: presubmit-e2e-test-release-1.23

  - name: openstack-cloud-csi-cinder-e2e-test-release-123
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    path_alias: "k8s.io/cloud-provider-openstack"
    always_run: false
    branches:
      - ^release-1.23$
    run_if_changed: '^(pkg\/util\/|pkg\/csi\/cinder\/|cmd\/cinder-csi-plugin\/|tests\/e2e\/csi\/cinder\/|manifests\/cinder-csi-plugin\/)'
    optional: false
    decorate: true
    decoration_config:
      timeout: 3h
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
          env:
          - name: "BOSKOS_HOST"
            value: "boskos.test-pods.svc.cluster.local"
          command:
          - "runner.sh"
          - "./tests/ci-csi-cinder-e2e.sh"
          securityContext:
            privileged: true
          resources:
            requests:
              memory: "1Gi"
              cpu: 1
    annotations:
      testgrid-dashboards: provider-openstack-openstack-csi-cinder
      testgrid-tab-name: presubmit-e2e-test-release-1.23

  - name: openstack-cloud-csi-manila-e2e-test-release-123
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    path_alias: "k8s.io/cloud-provider-openstack"
    always_run: false
    branches:
      - ^release-1.23$
    run_if_changed: '^(pkg\/util\/|pkg\/csi\/manila\/|cmd\/manila-csi-plugin\/|tests\/e2e\/csi\/manila\/)'
    optional: false
    decorate: true
    decoration_config:
      timeout: 3h
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
          env:
          - name: "BOSKOS_HOST"
            value: "boskos.test-pods.svc.cluster.local"
          command:
          - "runner.sh"
          - "./tests/ci-csi-manila-e2e.sh"
          securityContext:
            privileged: true
          resources:
            requests:
              memory: "1Gi"
              cpu: 1
    annotations:
      testgrid-dashboards: provider-openstack-manila-csi-plugin
      testgrid-tab-name: presubmit-e2e-test-release-1.23

  - name: openstack-cloud-csi-manila-sanity-test-release-123
    always_run: false
    run_if_changed: '^(pkg\/util\/|pkg\/csi\/manila\/|cmd\/manila-csi-plugin\/|tests\/sanity\/manila\/)'
    decorate: true
    branches:
      - ^release-1.23$
    path_alias: "k8s.io/cloud-provider-openstack"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        command:
        - make
        args:
        - test-manila-csi-sanity
    annotations:
      testgrid-dashboards: provider-openstack-manila-csi-plugin
      testgrid-tab-name: presubmit-sanity-test-release-1.23
      description: Run cloud-provider-openstack csi sanity tests for manila-csi-plugin
