presubmits:
  kubernetes/cloud-provider-openstack:
  - name: openstack-cloud-csi-cinder-sanity-test-release-122
    always_run: false
    run_if_changed: '^(pkg\/csi\/cinder\/|cmd\/cinder-csi-plugin\/|tests\/sanity\/cinder\/)'
    decorate: true
    branches:
      - ^release-1.22$
    path_alias: "k8s.io/cloud-provider-openstack"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        command:
        - make
        args:
        - test-cinder-csi-sanity
    annotations:
      testgrid-dashboards: provider-openstack-openstack-csi-cinder
      testgrid-tab-name: presubmit-sanity-test-release-1.22
      description: Run cloud-provider-openstack csi sanity tests for cinder-csi-plugin
