postsubmits:
  kubernetes-sigs/kueue:
    - name: post-kueue-push-images
      cluster: k8s-infra-prow-build-trusted
      annotations:
        testgrid-dashboards: sig-scheduling, sig-k8s-infra-gcb
      decorate: true
      branches:
        - ^main$
        - ^release-
        # Build semver tags, too
        - ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
      spec:
        serviceAccountName: gcb-builder
        containers:
          - image: gcr.io/k8s-staging-test-infra/image-builder:v20220428-ae431ed1aa
            command:
              - /run.sh
            args:
              - --project=k8s-staging-kueue
              - --scratch-bucket=gs://k8s-staging-kueue-gcb
              - --env-passthrough=PULL_BASE_REF
              - .
