postsubmits:
  kubernetes-sigs/etcdadm:
    - name: etcdadm-postsubmit-push-to-staging
      cluster: k8s-infra-prow-build-trusted
      annotations:
        testgrid-dashboards: sig-cluster-lifecycle-etcdadm, sig-k8s-infra-gcb
      decorate: true
      decoration_config:
        timeout: 20m
        grace_period: 5m
      branches:
        - ^master$
        - ^release-.*
        # Build (root) tags also
        # this is a regex for semver, from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
        - ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
        # Build etcd-manager tags
        - ^etcd-manager/.*$
      spec:
        serviceAccountName: gcb-builder
        containers:
          - image: gcr.io/k8s-staging-test-infra/image-builder:v20220428-ae431ed1aa
            command:
              - /run.sh
            args:
              # this is the project GCB will run in, which is the same as the GCR images are pushed to.
              - --project=k8s-staging-etcdadm
              - --scratch-bucket=gs://k8s-staging-etcdadm-gcb
              - --env-passthrough=PULL_BASE_REF
              - --with-git-dir
              - --build-dir=.
              - dev/staging/
