postsubmits:
  kubernetes-sigs/kind:
    - name: post-kind-push-binaries
      cluster: k8s-infra-prow-build-trusted
      annotations:
        testgrid-dashboards: sig-testing-kind, sig-k8s-infra-gcb
        testgrid-alert-email: kubernetes-engprod+alerts@google.com,antonio.ojea.garcia@gmail.com
        testgrid-num-columns-recent: '3'
      decorate: true
      spec:
        serviceAccountName: gcb-builder
        containers:
          - image: gcr.io/k8s-staging-test-infra/image-builder:v20220428-ae431ed1aa
            command:
              - /run.sh
            args:
              - --project=k8s-staging-kind
              - --scratch-bucket=gs://k8s-staging-kind-gcb
              - --env-passthrough=PULL_BASE_SHA
              - --build-dir=.
              - hack/ci/push-latest-cli/
            env:
              - name: LOG_TO_STDOUT
                value: "y"
      rerun_auth_config:
        github_team_ids:
          - 2921947 # kind-maintainers
