presubmits:
  kubernetes-sigs/metrics-server:
  - name: pull-metrics-server-verify
    decorate: true
    skip_branches:
      - gh-pages
      - release-0.3
    path_alias: sigs.k8s.io/metrics-server
    always_run: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        command:
        - runner.sh
        - make
        - verify
    annotations:
      testgrid-dashboards: sig-instrumentation-metrics-server
      testgrid-tab-name: pr-verify
  - name: pull-metrics-server-test-unit
    decorate: true
    skip_branches:
      - gh-pages
      - release-0.3
    path_alias: sigs.k8s.io/metrics-server
    always_run: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        command:
        - runner.sh
        - make
        - test-unit
        resources:
          requests:
            cpu: "6000m"
            memory: "6Gi"
    annotations:
      testgrid-dashboards: sig-instrumentation-metrics-server
      testgrid-tab-name: pr-test-unit
  - name: pull-metrics-server-test-version
    labels:
      preset-dind-enabled: "true"
    decorate: true
    skip_branches:
      - gh-pages
      - release-0.3
    path_alias: sigs.k8s.io/metrics-server
    always_run: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        command:
        - runner.sh
        - make
        - test-version
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "4000m"
            memory: "6Gi"
    annotations:
      testgrid-dashboards: sig-instrumentation-metrics-server
      testgrid-tab-name: pr-test-version
  - name: pull-metrics-server-test-e2e
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    decorate: true
    skip_branches:
      - gh-pages
      - release-0.3
    path_alias: sigs.k8s.io/metrics-server
    always_run: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        command:
          - runner.sh
          - make
          - test-e2e-all
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "6000m"
            memory: "6Gi"
    annotations:
      testgrid-dashboards: sig-instrumentation-metrics-server
      testgrid-tab-name: pr-test-e2e
  - name: pull-metrics-server-test-e2e-ha
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    decorate: true
    skip_branches:
      - gh-pages
      - release-0.3
      - release-0.4
      - release-0.5
    path_alias: sigs.k8s.io/metrics-server
    always_run: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        command:
          - runner.sh
          - make
          - test-e2e-ha-all
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "6000m"
            memory: "6Gi"
    annotations:
      testgrid-dashboards: sig-instrumentation-metrics-server
      testgrid-tab-name: pr-test-e2e-ha
  - name: pull-metrics-server-test-e2e-helm
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    decorate: true
    skip_branches:
      - gh-pages
      - release-0.3
      - release-0.4
      - release-0.5
    path_alias: sigs.k8s.io/metrics-server
    always_run: true
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
          command:
            - runner.sh
            - make
            - test-e2e-helm-all
          # we need privileged mode in order to do docker in docker
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "6000m"
              memory: "6Gi"
    annotations:
      testgrid-dashboards: sig-instrumentation-metrics-server
      testgrid-tab-name: pr-test-e2e-helm
