images:
  fedora:
    image_family: fedora-coreos-stable
    project: fedora-coreos-cloud
    machine: n1-standard-2
    metadata: "user-data</workspace/test-infra/jobs/e2e_node/crio/crio_cgrpv2_serial.ign"
