periodics:
- interval: 30m
  name: ci-kubernetes-e2e-gci-gce-statefulset
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=110
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --extract=ci/latest
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:StatefulSet\] --minStartupPods=8
      - --timeout=90m
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
  annotations:
    testgrid-dashboards: google-gce
    testgrid-tab-name: gci-gce-statefulset
