presubmits:
  kubernetes-sigs/gcp-filestore-csi-driver:
  - name: pull-gcp-filestore-csi-driver-e2e
    always_run: true
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/gcloud-in-go:v20220607-33951ed1ed
        args:
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--clean"
        - "--timeout=60" # Minutes
        - "--scenario=execute"
        - "--" # end bootstrap args, scenario args below
        - "test/run_e2e.sh"
        env:
        - name: ZONE
          value: us-central1-c
  - name: pull-gcp-filestore-csi-driver-sanity
    always_run: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/gcloud-in-go:v20220607-33951ed1ed
        args:
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--clean"
        - "--timeout=10" # Minutes
        - "--scenario=execute"
        - "--" # end bootstrap args, scenario args below
        - "test/run_sanity.sh"
  - name: pull-gcp-filestore-csi-driver-unit
    always_run: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/gcloud-in-go:v20220607-33951ed1ed
        args:
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--clean"
        - "--timeout=10" # Minutes
        - "--scenario=execute"
        - "--" # end bootstrap args, scenario args below
        - "test/run_unit.sh"
  - name: pull-gcp-filestore-csi-driver-verify
    always_run: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/gcloud-in-go:v20220607-33951ed1ed
        args:
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--clean"
        - "--timeout=10"
        - "--scenario=execute"
        - "--" # end bootstrap args, scenario args below
        - "hack/verify_all.sh"
  - name: pull-gcp-filestore-csi-driver-kubernetes-integration
    optional: true
    always_run: true
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        args:
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--clean"
        - "--timeout=180" # Minutes
        - "--scenario=execute"
        - "--" # end bootstrap args, scenario args below
        - "test/run-k8s-integration.sh"
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
      resources:
        requests:
          # these are both a bit below peak usage during build
          # this is mostly for building kubernetes
          memory: "9000Mi"
          # during the tests more like 3-20m is used
          cpu: 2000m
