# sigs.k8s.io/scheduler-plugins presubmits
presubmits:
  kubernetes-sigs/scheduler-plugins:
  - name: pull-scheduler-plugins-verify
    decorate: true
    path_alias: sigs.k8s.io/scheduler-plugins
    branches:
    - ^master$
    always_run: true
    spec:
      containers:
      - image: golang:1.17.11
        command:
        - make
        args:
        - verify
  - name: pull-scheduler-plugins-verify-build-master
    decorate: true
    path_alias: sigs.k8s.io/scheduler-plugins
    branches:
    - ^master$
    always_run: true
    spec:
      containers:
      - image: golang:1.17.11
        command:
        - make
        args:
        - build
  - name: pull-scheduler-plugins-unit-test-master
    decorate: true
    path_alias: sigs.k8s.io/scheduler-plugins
    branches:
    - ^master$
    always_run: true
    spec:
      containers:
      - image: golang:1.17.11
        command:
        - make
        args:
        - unit-test
  - name: pull-scheduler-plugins-integration-test-master
    decorate: true
    path_alias: sigs.k8s.io/scheduler-plugins
    branches:
    - ^master$
    always_run: true
    spec:
      containers:
      - image: golang:1.17.11
        command:
        - make
        args:
        - integration-test
