# sigs.k8s.io/scheduler-plugins presubmits
presubmits:
  kubernetes-sigs/scheduler-plugins:
  - name: pull-scheduler-plugins-verify-gofmt-release-1-22
    decorate: true
    path_alias: sigs.k8s.io/scheduler-plugins
    branches:
    - ^release-1.22$
    always_run: true
    spec:
      containers:
      - image: golang:1.16.7
        command:
        - make
        args:
        - verify
  - name: pull-scheduler-plugins-verify-build-release-1-22
    decorate: true
    path_alias: sigs.k8s.io/scheduler-plugins
    branches:
    - ^release-1.22$
    always_run: true
    spec:
      containers:
      - image: golang:1.16.7
        command:
        - make
        args:
        - build
  - name: pull-scheduler-plugins-unit-test-release-1-22
    decorate: true
    path_alias: sigs.k8s.io/scheduler-plugins
    branches:
    - ^release-1.22$
    always_run: true
    spec:
      containers:
      - image: golang:1.16.7
        command:
        - make
        args:
        - unit-test
  - name: pull-scheduler-plugins-integration-test-release-1-22
    decorate: true
    path_alias: sigs.k8s.io/scheduler-plugins
    branches:
    - ^release-1.22$
    always_run: true
    spec:
      containers:
      - image: golang:1.16.7
        command:
        - make
        args:
        - integration-test
