periodics:
- name: ci-gcp-compute-persistent-disk-csi-driver-release-k8s-master-integration
  interval: 4h
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
      args:
      - "--repo=sigs.k8s.io/gcp-compute-persistent-disk-csi-driver"
      - "--root=/go/src"
      - "--upload=gs://kubernetes-jenkins/logs"
      - "--clean"
      - "--timeout=180" # Minutes (120m runs consistently time out)
      - "--scenario=execute"
      - "--" # end bootstrap args, scenario args below
      - "test/run-k8s-integration-ci.sh"
      env:
      - name: GCE_PD_OVERLAY_NAME
        value: "stable-master"
      - name: GCE_PD_DO_DRIVER_BUILD
        value: "false"
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
      requests:
        # these are both a bit below peak usage during build
        # this is mostly for building kubernetes
        memory: "9000Mi"
        # during the tests more like 3-20m is used
        cpu: 2000m
  annotations:
    testgrid-dashboards: provider-gcp-compute-persistent-disk-csi-driver
    testgrid-tab-name: Kubernetes Master Driver Latest Release
    testgrid-alert-email: gke-managed-storage-alerts@google.com
    description: Kubernetes Integration tests for Kubernetes Master branch, Driver latest Release, and Stable Sidecars.  Used to verify stable is not broken by driver head.
- name: ci-gcp-compute-persistent-disk-csi-driver-release-staging-k8s-master-integration
  interval: 4h
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
      args:
      - "--repo=sigs.k8s.io/gcp-compute-persistent-disk-csi-driver"
      - "--root=/go/src"
      - "--upload=gs://kubernetes-jenkins/logs"
      - "--clean"
      - "--timeout=180" # Minutes (120m runs consistently time out)
      - "--scenario=execute"
      - "--" # end bootstrap args, scenario args below
      - "test/run-k8s-integration-ci.sh"
      env:
      - name: GCE_PD_OVERLAY_NAME
        value: "prow-stable-sidecar-rc-master"
      - name: GCE_PD_DO_DRIVER_BUILD
        value: "false"
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
      requests:
        # these are both a bit below peak usage during build
        # this is mostly for building kubernetes
        memory: "9000Mi"
        # during the tests more like 3-20m is used
        cpu: 2000m
  annotations:
    testgrid-dashboards: provider-gcp-compute-persistent-disk-csi-driver
    testgrid-tab-name: Kubernetes Master Driver Latest Release Candidate
    testgrid-alert-email: gke-managed-storage-alerts@google.com
    description: Kubernetes Integration tests for Kubernetes Master branch, Driver latest Release Candidate, and Stable Sidecars. Used to test release candidates when a new release is being cut.
- name: ci-gcp-compute-persistent-disk-csi-driver-latest-k8s-master-integration
  interval: 4h
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
      args:
      - "--repo=sigs.k8s.io/gcp-compute-persistent-disk-csi-driver"
      - "--root=/go/src"
      - "--upload=gs://kubernetes-jenkins/logs"
      - "--clean"
      - "--timeout=180" # Minutes (120m times out)
      - "--scenario=execute"
      - "--" # end bootstrap args, scenario args below
      - "test/run-k8s-integration-ci.sh"
      env:
      - name: GCE_PD_OVERLAY_NAME
        value: "dev"
      - name: GCE_PD_DO_DRIVER_BUILD
        value: "true"
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
      requests:
        # these are both a bit below peak usage during build
        # this is mostly for building kubernetes
        memory: "9000Mi"
        # during the tests more like 3-20m is used
        cpu: 2000m
  annotations:
    testgrid-dashboards: provider-gcp-compute-persistent-disk-csi-driver
    testgrid-tab-name: Kubernetes Master Driver Latest
    testgrid-alert-email: gke-managed-storage-alerts@google.com
    description: Kubernetes Integration tests for Kubernetes Master branch, Driver latest build, and Stable Sidecars
- name: ci-gcp-compute-persistent-disk-csi-driver-latest-k8s-master-integration-canary-sidecars
  interval: 4h
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
      args:
      - "--repo=sigs.k8s.io/gcp-compute-persistent-disk-csi-driver"
      - "--root=/go/src"
      - "--upload=gs://kubernetes-jenkins/logs"
      - "--clean"
      - "--timeout=180" # Minutes (120m times out)
      - "--scenario=execute"
      - "--" # end bootstrap args, scenario args below
      - "test/run-k8s-integration-ci.sh"
      env:
      - name: GCE_PD_OVERLAY_NAME
        value: "prow-canary-sidecar"
      - name: GCE_PD_DO_DRIVER_BUILD
        value: "true"
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
      requests:
        # these are both a bit below peak usage during build
        # this is mostly for building kubernetes
        memory: "9000Mi"
        # during the tests more like 3-20m is used
        cpu: 2000m
  annotations:
    testgrid-dashboards: provider-gcp-compute-persistent-disk-csi-driver
    testgrid-tab-name: Kubernetes Master Driver Latest Canary Sidecars
    testgrid-alert-email: gke-managed-storage-alerts@google.com
    description: Kubernetes Integration tests for Kubernetes Master branch, Driver latest build, and Canary Sidecars. Used to test the latest sidecars.
- name: ci-gcp-compute-persistent-disk-csi-driver-stable-k8s-master-migration
  interval: 4h
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
      args:
      - "--repo=sigs.k8s.io/gcp-compute-persistent-disk-csi-driver"
      - "--root=/go/src"
      - "--upload=gs://kubernetes-jenkins/logs"
      - "--clean"
      - "--timeout=180" # Minutes
      - "--scenario=execute"
      - "--" # end bootstrap args, scenario args below
      - "test/run-k8s-integration-migration.sh"
      env:
      - name: GCE_PD_OVERLAY_NAME
        value: "stable-master"
      - name: GCE_PD_DO_DRIVER_BUILD
        value: "false"
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
    resources:
      requests:
        # these are both a bit below peak usage during build
        # this is mostly for building kubernetes
        memory: "9000Mi"
        # during the tests more like 3-20m is used
        cpu: 2000m
  annotations:
    testgrid-dashboards: provider-gcp-compute-persistent-disk-csi-driver
    testgrid-tab-name: Migration Kubernetes Master Driver Stable
    testgrid-alert-email: gke-managed-storage-alerts@google.com
    description: Kubernetes in-tree E2E tests with CSIMigration on for Kubernetes Master branch and Driver Stable
- name: ci-gcp-compute-persistent-disk-csi-driver-latest-k8s-master-migration
  interval: 1h
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
      args:
      - "--repo=sigs.k8s.io/gcp-compute-persistent-disk-csi-driver"
      - "--root=/go/src"
      - "--upload=gs://kubernetes-jenkins/logs"
      - "--clean"
      - "--timeout=180" # Minutes
      - "--scenario=execute"
      - "--" # end bootstrap args, scenario args below
      - "test/run-k8s-integration-migration.sh"
      env:
      - name: GCE_PD_OVERLAY_NAME
        value: "dev"
      - name: GCE_PD_DO_DRIVER_BUILD
        value: "true"
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
    resources:
      requests:
        # these are both a bit below peak usage during build
        # this is mostly for building kubernetes
        memory: "9000Mi"
        # during the tests more like 3-20m is used
        cpu: 2000m
  annotations:
    testgrid-dashboards: provider-gcp-compute-persistent-disk-csi-driver
    testgrid-tab-name: Migration Kubernetes Master Driver Latest
    testgrid-alert-email: gke-managed-storage-alerts@google.com
    description: Kubernetes in-tree E2E tests with CSIMigration on for Kubernetes Master branch and Driver latest build
