presubmits:
  kubernetes-sigs/oci-proxy:
  - name: pull-oci-proxy-verify
    cluster: k8s-infra-prow-build
    decorate: true
    always_run: true
    annotations:
      testgrid-dashboards: sig-k8s-infra-oci-proxy
      testgrid-tab-name: pull-oci-proxy-verify
      testgrid-num-failures-to-alert: '6'
      testgrid-alert-email: k8s-infra-alerts@kubernetes.io
    spec:
      containers:
      - image: golang
        command:
        - make
        - verify
        # shellcheck has its own job so we don't need docker
        - VERIFY_SHELLCHECK=false
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
  - name: pull-oci-proxy-shellcheck
    cluster: k8s-infra-prow-build
    decorate: true
    always_run: true
    annotations:
      testgrid-dashboards: sig-k8s-infra-oci-proxy
      testgrid-tab-name: pull-oci-proxy-shellcheck
      testgrid-num-failures-to-alert: '6'
      testgrid-alert-email: k8s-infra-alerts@kubernetes.io
    spec:
      containers:
      - image: golang
        command:
        - bash
        - -c
        - hack/tools/ci-install-shellcheck.sh && make shellcheck
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
  - name: pull-oci-proxy-test
    cluster: k8s-infra-prow-build
    decorate: true
    always_run: true
    annotations:
      testgrid-dashboards: sig-k8s-infra-oci-proxy
      testgrid-tab-name: pull-oci-proxy-test
      testgrid-num-failures-to-alert: '6'
      testgrid-alert-email: k8s-infra-alerts@kubernetes.io
    spec:
      containers:
      - image: golang
        command:
        - make
        - test
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
  - name: pull-oci-proxy-build
    decorate: true
    always_run: true
    annotations:
      testgrid-dashboards: sig-k8s-infra-oci-proxy
      testgrid-tab-name: pull-oci-proxy-build
      testgrid-num-failures-to-alert: '6'
      testgrid-alert-email: k8s-infra-alerts@kubernetes.io
    spec:
      containers:
      - image: golang
        command:
        - make
        - images
        - build
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
