presubmits:
  kubernetes-sigs/cloud-provider-azure:
    - name: pull-cloud-provider-azure-check-1-23
      skip_if_only_changed: "^docs/|^site/|^\\.github/|\\.(md|adoc)$|^(README|LICENSE)$"
      decorate: true
      path_alias: sigs.k8s.io/cloud-provider-azure
      branches:
        - release-1.23
      labels:
        preset-service-account: "true"
      spec:
        containers:
          - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
            command:
              - runner.sh
            args:
              - make
              - test-check
            resources:
              limits:
                memory: "9Gi"
                cpu: "2"
              requests:
                memory: "9Gi"
                cpu: "2"
      annotations:
        testgrid-dashboards: provider-azure-cloud-provider-azure-1-23-presubmit
        testgrid-tab-name: pr-cloud-provider-azure-check-1-23
        description: "Run lint check tests for cloud-provider-azure release-1.23."
        testgrid-num-columns-recent: '30'
    # pull-cloud-provider-azure-e2e-ccm-vmss-basic-lb-1-23 runs Azure specific e2e tests with VMSS and basic loadbalancer.
    - name: pull-cloud-provider-azure-e2e-ccm-vmss-basic-lb-1-23
      skip_if_only_changed: "^docs/|^site/|^\\.github/|\\.(md|adoc)$|^(README|LICENSE)$"
      decorate: true
      decoration_config:
        timeout: 5h
      path_alias: sigs.k8s.io/cloud-provider-azure
      branches:
        - release-1.23
      labels:
        preset-service-account: "true"
        preset-azure-cred: "true"
        preset-dind-enabled: "true"
      extra_refs:
        - org: kubernetes
          repo: kubernetes
          base_ref: release-1.23
          path_alias: k8s.io/kubernetes
          workdir: true
      spec:
        containers:
          - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.23
            command:
              - runner.sh
              - kubetest
            args:
              # Generic e2e test args
              - --test
              - --up
              - --down
              - --build=quick
              - --dump=$(ARTIFACTS)
              # Azure-specific test args
              - --provider=skeleton
              - --deployment=aksengine
              - --aksengine-agentpoolcount=2
              - --aksengine-admin-username=azureuser
              - --aksengine-creds=$(AZURE_CREDENTIALS)
              - --aksengine-orchestratorRelease=1.23
              - --aksengine-mastervmsize=Standard_DS2_v2
              - --aksengine-agentvmsize=Standard_D4s_v3
              - --aksengine-ccm
              - --aksengine-cnm
              - --aksengine-deploy-custom-k8s
              - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
              - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/tests/k8s-azure/manifest/linux-vmss-basic-lb.json
              - --aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/nightly/aks-engine-nightly-linux-amd64.tar.gz
              # Specific test args
              - --test-ccm
              - --ginkgo-parallel=30
            securityContext:
              privileged: true
            env:
              - name: AZURE_LOADBALANCER_SKU
                value: "basic"
      annotations:
        testgrid-dashboards: provider-azure-cloud-provider-azure-1-23-presubmit
        testgrid-tab-name: pr-cloud-provider-azure-e2e-ccm-vmss-basic-lb-1-23
        description: "Runs Azure specific tests (VMSS + basic LB) with cloud-provider-azure release-1.23 (https://github.com/kubernetes-sigs/cloud-provider-azure)."
        testgrid-num-columns-recent: '30'
    # pull-cloud-provider-azure-e2e-ccm-vmss-capz-1-23
    - name: pull-cloud-provider-azure-e2e-ccm-vmss-capz-1-23
      skip_if_only_changed: "^docs/|^site/|^\\.github/|\\.(md|adoc)$|^(README|LICENSE)$"
      decorate: true
      decoration_config:
        timeout: 3h
      path_alias: sigs.k8s.io/cloud-provider-azure
      branches:
        - release-1.23
      labels:
        preset-dind-enabled: "true"
        preset-kind-volume-mounts: "true"
        preset-azure-cred-only: "true"
        preset-azure-anonymous-pull: "true"
      extra_refs:
        - org: kubernetes-sigs
          repo: cluster-api-provider-azure
          base_ref: release-1.4
          path_alias: sigs.k8s.io/cluster-api-provider-azure
          workdir: true
      spec:
        containers:
          - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
            command:
              - runner.sh
              - ./scripts/ci-entrypoint.sh
            args:
              - bash
              - -c
              - >-
                cd ${GOPATH}/src/sigs.k8s.io/cloud-provider-azure &&
                make test-ccm-e2e
            securityContext:
              privileged: true
            env:
              - name: TEST_CCM
                value: "true"
              - name: KUBERNETES_VERSION
                value: "1.23.5"
              - name: CONTROL_PLANE_MACHINE_COUNT
                value: "1"
              - name: CLUSTER_TEMPLATE
                value: https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/tests/k8s-azure/manifest/cluster-api/linux-vmss.yaml
              - name: AZURE_LOADBALANCER_SKU
                value: "Standard"
              - name: K8S_FEATURE_GATES
                value: "MixedProtocolLBService=true"
      annotations:
        testgrid-dashboards: provider-azure-cloud-provider-azure-1-23-presubmit
        testgrid-tab-name: pr-cloud-provider-azure-e2e-ccm-vmss-capz-1-23
        description: "Runs Azure specific tests with cloud-provider-azure release-1.23 (https://github.com/kubernetes-sigs/cloud-provider-azure) on vmss, using cluster-api-provider-azure."
        testgrid-num-columns-recent: '30'
    # pull-cloud-provider-azure-e2e-capz-1-23 runs kubernetes conformance tests.
    - name: pull-cloud-provider-azure-e2e-capz-1-23
      skip_if_only_changed: "^docs/|^site/|^tests/e2e/|^\\.github/|\\.(md|adoc)$|^(README|LICENSE)$"
      decorate: true
      decoration_config:
        timeout: 5h
      path_alias: sigs.k8s.io/cloud-provider-azure
      branches:
        - release-1.23
      labels:
        preset-dind-enabled: "true"
        preset-kind-volume-mounts: "true"
        preset-azure-cred-only: "true"
        preset-azure-anonymous-pull: "true"
      extra_refs:
        - org: kubernetes-sigs
          repo: cluster-api-provider-azure
          base_ref: release-1.4
          path_alias: sigs.k8s.io/cluster-api-provider-azure
          workdir: true
        - org: kubernetes
          repo: kubernetes
          base_ref: release-1.23
          path_alias: k8s.io/kubernetes
          workdir: false
      spec:
        containers:
          - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
            command:
              - runner.sh
              - ./scripts/ci-entrypoint.sh
            args:
              - bash
              - -c
              - >-
                cp ./kubeconfig ${GOPATH}/src/sigs.k8s.io/cloud-provider-azure/kubeconfig &&
                cd ${GOPATH}/src/sigs.k8s.io/cloud-provider-azure &&
                make test-e2e-capz
            securityContext:
              privileged: true
            env:
              - name: TEST_CCM
                value: "true"
              - name: AZURE_LOADBALANCER_SKU
                value: "standard"
              - name: KUBERNETES_VERSION
                value: "latest-1.23"
              - name: GINKGO_ARGS
                value: --ginkgo.focus=\[Conformance\]|\[NodeConformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|\[Flaky\] --test.parallel=30 --report-dir=/logs/artifacts --disable-log-dump=true
              - name: CONTROL_PLANE_MACHINE_COUNT
                value: "1"
      annotations:
        testgrid-dashboards: provider-azure-cloud-provider-azure-1-23-presubmit
        testgrid-tab-name: pr-cloud-provider-azure-e2e-capz-1-23
        description: "Runs Kubernetes conformance tests with cloud-provider-azure release-1.23 (https://github.com/kubernetes-sigs/cloud-provider-azure) using cluster-api-provider-azure."
        testgrid-num-columns-recent: '30'
    # pull-cloud-provider-azure-e2e-ccm-capz-1-23
    - name: pull-cloud-provider-azure-e2e-ccm-capz-1-23
      skip_if_only_changed: "^docs/|^site/|^\\.github/|\\.(md|adoc)$|^(README|LICENSE)$"
      decorate: true
      decoration_config:
        timeout: 3h
      path_alias: sigs.k8s.io/cloud-provider-azure
      branches:
        - release-1.23
      labels:
        preset-dind-enabled: "true"
        preset-kind-volume-mounts: "true"
        preset-azure-cred-only: "true"
        preset-azure-anonymous-pull: "true"
      extra_refs:
        - org: kubernetes-sigs
          repo: cluster-api-provider-azure
          base_ref: release-1.4
          path_alias: sigs.k8s.io/cluster-api-provider-azure
          workdir: true
      spec:
        containers:
          - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
            command:
              - runner.sh
              - ./scripts/ci-entrypoint.sh
            args:
              - bash
              - -c
              - >-
                cd ${GOPATH}/src/sigs.k8s.io/cloud-provider-azure &&
                make test-ccm-e2e
            securityContext:
              privileged: true
            env:
              - name: TEST_CCM
                value: "true"
              - name: AZURE_LOADBALANCER_SKU
                value: "standard"
              - name: KUBERNETES_VERSION
                value: "latest-1.23"
              - name: CONTROL_PLANE_MACHINE_COUNT
                value: "1"
              - name: K8S_FEATURE_GATES
                value: "MixedProtocolLBService=true"
      annotations:
        testgrid-dashboards: provider-azure-cloud-provider-azure-1-23-presubmit
        testgrid-tab-name: pr-cloud-provider-azure-e2e-ccm-capz-1-23
        description: "Runs Azure specific tests with cloud-provider-azure release-1.23 (https://github.com/kubernetes-sigs/cloud-provider-azure) using cluster-api-provider-azure."
        testgrid-num-columns-recent: '30'
    - name: pull-cloud-provider-azure-unit-1-23
      skip_if_only_changed: "^docs/|^site/|^tests/e2e/|^\\.github/|\\.(md|adoc)$|^(README|LICENSE)$"
      decorate: true
      path_alias: sigs.k8s.io/cloud-provider-azure
      branches:
        - release-1.23
      labels:
        preset-service-account: "true"
      spec:
        containers:
          - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
            command:
              - runner.sh
            args:
              - make
              - test-unit
      annotations:
        testgrid-dashboards: provider-azure-cloud-provider-azure-1-23-presubmit
        testgrid-tab-name: pr-cloud-provider-azure-unit-1-23
        description: "Run unit tests for cloud-provider-azure release-1.23."
        testgrid-num-columns-recent: '30'
