# To copy an image between projects:
# `gcloud compute --project <to-project> disks create <image name> --image=https://www.googleapis.com/compute/v1/projects/<from-project>/global/images/<image-name>`
# `gcloud compute --project <to-project> images create <image-name> --source-disk=<image-name>`
images:
  ubuntu:
    image: ubuntu-gke-2204-1-24-v20220623
    machine: n1-standard-2 # These tests need a lot of memory
    project: ubuntu-os-gke-cloud
  cos-stable2:
    image_family: cos-93-lts # deprecated after October 2023 (https://cloud.google.com/container-optimized-os/docs/release-notes)
    project: cos-cloud
    machine: n1-standard-2 # These tests need a lot of memory
    metadata: "user-data<test/e2e_node/jenkins/gci-init-gpu.yaml,gci-update-strategy=update_disabled"
    resources:
      accelerators:
        - type: nvidia-tesla-k80
          count: 2
  cos-stable1:
    image_family: cos-89-lts # deprecated after March 2023 (https://cloud.google.com/container-optimized-os/docs/release-notes)
    project: cos-cloud
    machine: n1-standard-2 # These tests need a lot of memory
    metadata: "user-data<test/e2e_node/jenkins/cos-init-live-restore.yaml,gci-update-strategy=update_disabled"
