periodics:
- name: ci-kubernetes-storage-scalability
  tags:
    - "perfDashPrefix: storage"
    - "perfDashJobType: storage"
  interval: 6h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-e2e-scalability-node: "true"
    preset-e2e-scalability-periodics: "true"
    preset-e2e-scalability-periodics-master: "true"
  decorate: true
  decoration_config:
    timeout: 360m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  - org: kubernetes
    repo: perf-tests
    base_ref: master
    path_alias: k8s.io/perf-tests
  annotations:
    testgrid-dashboards: sig-scalability-experiments
    testgrid-tab-name: storage
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
      command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --check-leaked-resources
      - --cluster=
      - --extract=ci/latest
      - --gcp-node-image=gci
      - --gcp-nodes=1
      - --provider=gce
      - --test=false
      - --test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh
      - --test-cmd-args=cluster-loader2
      - --test-cmd-args=--nodes=1
      - --test-cmd-args=--provider=gce
      - --test-cmd-args=--report-dir=$(ARTIFACTS)
      - --test-cmd-args=--testsuite=testing/experimental/storage/pod-startup/suite.yaml
      - --test-cmd-name=ClusterLoaderV2
      - --timeout=300m
      - --use-logexporter
      - --logexporter-gcs-path=gs://sig-scalability-logs/$(JOB_NAME)/$(BUILD_ID)

- name: ci-kubernetes-e2e-gci-gce-scalability-networkpolicies
  cluster: k8s-infra-prow-build
  interval: 6h
  tags:
    - "perfDashPrefix: networkpolicies"
    - "perfDashJobType: networkpolicies"
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-e2e-scalability-common: "true"
    preset-e2e-scalability-periodics: "true"
    preset-e2e-scalability-periodics-master: "true"
  decorate: true
  decoration_config:
    timeout: 140m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  - org: kubernetes
    repo: perf-tests
    base_ref: master
    path_alias: k8s.io/perf-tests
  annotations:
    testgrid-dashboards: sig-scalability-experiments
    testgrid-tab-name: calico
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
      command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      env:
      - name: NETWORK_POLICY_PROVIDER
        value: "calico"
      - name: ADDITIONAL_MACHINE_TYPE
        value: "e2-standard-2"
      - name: NUM_ADDITIONAL_NODES
        value: "4"
      args:
      - --check-leaked-resources
      - --cluster=e2e-scalability-calico
      - --env=CL2_ENABLE_NETWORKPOLICIES=true
      - --extract=ci/latest
      - --gcp-node-image=gci
      - --gcp-nodes=100
      - --gcp-project-type=scalability-project
      - --gcp-zone=us-east1-b
      - --provider=gce
      - --env=CL2_SCHEDULER_THROUGHPUT_THRESHOLD=0
      - --test=false
      - --test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh
      - --test-cmd-args=cluster-loader2
      - --test-cmd-args=--experimental-gcp-snapshot-prometheus-disk=true
      - --test-cmd-args=--experimental-prometheus-disk-snapshot-name=ci-kubernetes-e2e-gci-gce-scalability-np-$(BUILD_ID)
      - --test-cmd-args=--experimental-prometheus-snapshot-to-report-dir=true
      - --test-cmd-args=--nodes=100
      - --test-cmd-args=--prometheus-scrape-node-exporter
      - --test-cmd-args=--provider=gce
      - --test-cmd-args=--report-dir=$(ARTIFACTS)
      - --test-cmd-args=--testconfig=testing/load/config.yaml
      - --test-cmd-args=--testconfig=testing/huge-service/config.yaml
      - --test-cmd-args=--testoverrides=./testing/experiments/use_simple_latency_query.yaml
      - --test-cmd-name=ClusterLoaderV2
      - --timeout=120m
      - --use-logexporter
      - --logexporter-gcs-path=gs://k8s-infra-scalability-tests-logs/$(JOB_NAME)/$(BUILD_ID)
      resources:
        limits:
          cpu: 2
          memory: "6Gi"
        requests:
          cpu: 2
          memory: "6Gi"

  # Experimental job confirming that node killer works. Fork of ci-kubernetes-e2e-gci-gce-scalability.
  # To be removed after Chaos Monkey flags are enabled in ci-kubernetes-e2e-gci-gce-scalability
- interval: 6h
  name: ci-kubernetes-e2e-gci-gce-scalability-node-killer
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-e2e-scalability-common: "true"
    preset-e2e-scalability-periodics: "true"
    preset-e2e-scalability-periodics-master: "true"
  decorate: true
  decoration_config:
    timeout: 140m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  - org: kubernetes
    repo: perf-tests
    base_ref: master
    path_alias: k8s.io/perf-tests
  annotations:
    testgrid-dashboards: sig-scalability-experiments
    testgrid-tab-name: gce-cos-master-scalability-100-nodekiller
  spec:
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
          - --check-leaked-resources
          - --cluster=e2e-big
          - --extract=ci/latest
          - --gcp-node-image=gci
          - --gcp-nodes=100
          - --gcp-project-type=scalability-project
          - --gcp-zone=us-east1-b
          - --provider=gce
          - --env=APISERVER_TEST_ARGS=--max-requests-inflight=80 --max-mutating-requests-inflight=0
          - --env=CL2_ENABLE_VIOLATIONS_FOR_SCHEDULING_THROUGHPUT=false
          - --test=false
          - --test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh
          - --test-cmd-args=cluster-loader2
          - --test-cmd-args=--experimental-gcp-snapshot-prometheus-disk=true
          - --test-cmd-args=--experimental-prometheus-disk-snapshot-name=$(JOB_NAME)-$(BUILD_ID)
          - --test-cmd-args=--experimental-prometheus-snapshot-to-report-dir=true
          - --test-cmd-args=--nodes=100
          - --test-cmd-args=--prometheus-scrape-node-exporter
          - --test-cmd-args=--provider=gce
          - --test-cmd-args=--report-dir=$(ARTIFACTS)
          - --test-cmd-args=--testconfig=testing/load/config.yaml
          - --test-cmd-args=--testconfig=testing/huge-service/config.yaml
          - --test-cmd-args=--testoverrides=./testing/chaosmonkey/override.yaml
          - --test-cmd-args=--testoverrides=./testing/chaosmonkey/ignore_node_killer_container_restarts_100.yaml
          - --test-cmd-args=--testoverrides=./testing/experiments/enable_restart_count_check.yaml
          - --test-cmd-args=--testoverrides=./testing/experiments/use_simple_latency_query.yaml
          - --test-cmd-args=--testoverrides=./testing/overrides/load_throughput.yaml
          - --test-cmd-name=ClusterLoaderV2
          - --timeout=120m
          - --use-logexporter
          - --logexporter-gcs-path=gs://sig-scalability-logs/$(JOB_NAME)/$(BUILD_ID)
