periodics:
- name: periodic-cluster-api-test-release-1-0
  interval: 12h
  decorate: true
  decoration_config:
    gcs_credentials_secret: "" # Use workload identity for uploading artifacts
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: release-1.0
    path_alias: sigs.k8s.io/cluster-api
  spec:
    serviceAccountName: prowjob-default-sa
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.22
      command:
      - "./scripts/ci-test.sh"
      resources:
        requests:
          cpu: 7300m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-1.0
    testgrid-tab-name: capi-test-release-1-0
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "4"
- name: periodic-cluster-api-e2e-upgrade-v0-3-to-release-1-0
  interval: 12h
  decorate: true
  decoration_config:
    gcs_credentials_secret: "" # Use workload identity for uploading artifacts
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: release-1.0
    path_alias: sigs.k8s.io/cluster-api
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    serviceAccountName: prowjob-default-sa
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.22
        args:
          - runner.sh
          - "./scripts/ci-e2e.sh"
        env:
          - name: GINKGO_FOCUS
            value: "\\[clusterctl-Upgrade\\]"
          - name: INIT_WITH_BINARY
            value: https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.3.25/clusterctl-{OS}-{ARCH}
          - name: INIT_WITH_PROVIDERS_CONTRACT
            value: v1alpha3
          - name: INIT_WITH_KUBERNETES_VERSION
            value: v1.21.2

        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 7300m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-1.0
    testgrid-tab-name: capi-e2e-upgrade-v0-3-to-release-1-0
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "4"
- name: periodic-cluster-api-e2e-release-1-0
  interval: 12h
  decorate: true
  decoration_config:
    gcs_credentials_secret: "" # Use workload identity for uploading artifacts
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: release-1.0
    path_alias: sigs.k8s.io/cluster-api
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    serviceAccountName: prowjob-default-sa
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.22
        args:
          - runner.sh
          - "./scripts/ci-e2e.sh"
        env:
          - name: GINKGO_SKIP
            value: "\\[Conformance\\] \\[K8s-Upgrade\\]"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 7300m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-1.0
    testgrid-tab-name: capi-e2e-release-1-0
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "4"
- name: periodic-cluster-api-e2e-mink8s-release-1-0
  interval: 12h
  decorate: true
  decoration_config:
    gcs_credentials_secret: "" # Use workload identity for uploading artifacts
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: release-1.0
    path_alias: sigs.k8s.io/cluster-api
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    serviceAccountName: prowjob-default-sa
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.22
      args:
      - runner.sh
      - "./scripts/ci-e2e.sh"
      env:
      - name: GINKGO_SKIP
        value: "\\[Conformance\\] \\[K8s-Upgrade\\]"
      # This value determines the minimum Kubernetes
      # supported version for Cluster API management cluster.
      - name: KUBERNETES_VERSION_MANAGEMENT
        value: "stable-1.19"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 7300m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-1.0
    testgrid-tab-name: capi-e2e-mink8s-release-1-0
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "4"
- name: periodic-cluster-api-verify-book-links-release-1-0
  interval: 24h
  decorate: true
  decoration_config:
    gcs_credentials_secret: "" # Use workload identity for uploading artifacts
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: release-1.0
    path_alias: sigs.k8s.io/cluster-api
  spec:
    serviceAccountName: prowjob-default-sa
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.22
      command:
      - "runner.sh"
      - "make"
      - "verify-book-links"
      env:
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: cluster-lifecycle-github-token
            key: cluster-lifecycle-github-token
  volumes:
  - name: cluster-lifecycle-github-token
    secret:
      secretName: cluster-lifecycle-github-token
      items:
      - key: cluster-lifecycle-github-token
        path: cluster-lifecycle-github-token
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-1.0
    testgrid-tab-name: capi-verify-book-links-release-1-0
