presubmits:
  kubernetes-sigs/cluster-api:
  - name: pull-cluster-api-build-main
    decorate: true
    decoration_config:
      gcs_credentials_secret: "" # Use workload identity for uploading artifacts
    path_alias: sigs.k8s.io/cluster-api
    always_run: true
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    spec:
      serviceAccountName: prowjob-default-sa
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
        command:
        - runner.sh
        - ./scripts/ci-build.sh
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api
      testgrid-tab-name: capi-pr-build-main
  - name: pull-cluster-api-apidiff-main
    decorate: true
    decoration_config:
      gcs_credentials_secret: "" # Use workload identity for uploading artifacts
    path_alias: sigs.k8s.io/cluster-api
    always_run: true
    optional: true
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    spec:
      serviceAccountName: prowjob-default-sa
      containers:
      - command:
        - runner.sh
        - ./scripts/ci-apidiff.sh
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api
      testgrid-tab-name: capi-pr-apidiff-main
  - name: pull-cluster-api-verify-main
    decorate: true
    decoration_config:
      gcs_credentials_secret: "" # Use workload identity for uploading artifacts
    path_alias: sigs.k8s.io/cluster-api
    always_run: true
    labels:
      preset-dind-enabled: "true"
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    spec:
      serviceAccountName: prowjob-default-sa
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
        command:
        - "runner.sh"
        - ./scripts/ci-verify.sh
        resources:
          requests:
            cpu: 7300m
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api
      testgrid-tab-name: capi-pr-verify-main
  - name: pull-cluster-api-test-main
    decorate: true
    decoration_config:
      gcs_credentials_secret: "" # Use workload identity for uploading artifacts
    path_alias: sigs.k8s.io/cluster-api
    always_run: true
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    spec:
      serviceAccountName: prowjob-default-sa
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
        args:
        - runner.sh
        - ./scripts/ci-test.sh
        resources:
          requests:
            cpu: 7300m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api
      testgrid-tab-name: capi-pr-test-main
  - name: pull-cluster-api-test-mink8s-main
    decorate: true
    decoration_config:
      gcs_credentials_secret: "" # Use workload identity for uploading artifacts
    path_alias: sigs.k8s.io/cluster-api
    always_run: true
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    spec:
      serviceAccountName: prowjob-default-sa
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
        args:
        - runner.sh
        - ./scripts/ci-test.sh
        env:
        # This value determines the minimum Kubernetes
        # supported version for Cluster API management cluster.
        #
        # To check the available envtest in Kubebuilder, please
        # refer to https://github.com/kubernetes-sigs/kubebuilder/tree/tools-releases.
        - name: KUBEBUILDER_ENVTEST_KUBERNETES_VERSION
          value: "1.20.2"
        resources:
          requests:
            cpu: 7300m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api
      testgrid-tab-name: capi-pr-test-mink8s-main
  - name: pull-cluster-api-e2e-main
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    decorate: true
    decoration_config:
      gcs_credentials_secret: "" # Use workload identity for uploading artifacts
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    path_alias: sigs.k8s.io/cluster-api
    run_if_changed: '^((api|bootstrap|cmd|config|controllers|controlplane|errors|exp|feature|hack|internal|scripts|test|third_party|util|webhooks|version)/|main\.go|go\.mod|go\.sum|Dockerfile|Makefile)'
    spec:
      serviceAccountName: prowjob-default-sa
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
        args:
          - runner.sh
          - "./scripts/ci-e2e.sh"
        env:
          - name: GINKGO_FOCUS
            value: "\\[PR-Blocking\\]"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 7300m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api
      testgrid-tab-name: capi-pr-e2e-main
  - name: pull-cluster-api-e2e-informing-main
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    decorate: true
    decoration_config:
      gcs_credentials_secret: "" # Use workload identity for uploading artifacts
    optional: true
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    path_alias: sigs.k8s.io/cluster-api
    run_if_changed: '^((api|bootstrap|cmd|config|controllers|controlplane|errors|exp|feature|hack|internal|scripts|test|third_party|util|webhooks|version)/|main\.go|go\.mod|go\.sum|Dockerfile|Makefile)'
    spec:
      serviceAccountName: prowjob-default-sa
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
        args:
        - runner.sh
        - "./scripts/ci-e2e.sh"
        env:
        - name: GINKGO_FOCUS
          value: "\\[PR-Informing\\]"
        - name: GINKGO_SKIP
          value: "\\[IPv6\\]"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 7300m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api
      testgrid-tab-name: capi-pr-e2e-informing-main
  - name: pull-cluster-api-e2e-informing-ipv6-main
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    decorate: true
    decoration_config:
      gcs_credentials_secret: "" # Use workload identity for uploading artifacts
    optional: true
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    path_alias: sigs.k8s.io/cluster-api
    run_if_changed: '^((api|bootstrap|cmd|config|controllers|controlplane|errors|exp|feature|hack|internal|scripts|test|third_party|util|webhooks|version)/|main\.go|go\.mod|go\.sum|Dockerfile|Makefile)'
    spec:
      serviceAccountName: prowjob-default-sa
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
        args:
          - runner.sh
          - "./scripts/ci-e2e.sh"
        env:
          # enable IPV6 in bootstrap image
          - name: "DOCKER_IN_DOCKER_IPV6_ENABLED"
            value: "true"
          - name: GINKGO_FOCUS
            value: "\\[IPv6\\] \\[PR-Informing\\]"
          - name: IP_FAMILY
            value: "IPv6"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 7300m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api
      testgrid-tab-name: capi-pr-e2e-informing-ipv6-main
  - name: pull-cluster-api-e2e-full-main
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    decorate: true
    decoration_config:
      gcs_credentials_secret: "" # Use workload identity for uploading artifacts
    optional: true
    always_run: false
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    path_alias: sigs.k8s.io/cluster-api
    spec:
      serviceAccountName: prowjob-default-sa
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
        args:
          - runner.sh
          - "./scripts/ci-e2e.sh"
        env:
          # Since the PR-Blocking tests are run as part of the cluster-api-test-main job
          # and the upgrade tests are being run as part of the periodic upgrade jobs.
          # This jobs ends up running all the other tests in the E2E suite
          - name: GINKGO_SKIP
            value: "\\[PR-Blocking\\] \\[Conformance\\] \\[K8s-Upgrade\\]|\\[IPv6\\]"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 7300m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api
      testgrid-tab-name: capi-pr-e2e-full-main
  - name: pull-cluster-api-e2e-workload-upgrade-1-24-latest-main
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    decorate: true
    decoration_config:
      gcs_credentials_secret: "" # Use workload identity for uploading artifacts
    optional: true
    always_run: false
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    path_alias: sigs.k8s.io/cluster-api
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
    spec:
      serviceAccountName: prowjob-default-sa
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
        args:
          - runner.sh
          - "./scripts/ci-e2e.sh"
        env:
          - name: KUBERNETES_VERSION_UPGRADE_FROM
            value: "stable-1.24"
          - name: KUBERNETES_VERSION_UPGRADE_TO
            value: "ci/latest-1.25"
          - name: ETCD_VERSION_UPGRADE_TO
            value: "3.5.3-0"
          - name: COREDNS_VERSION_UPGRADE_TO
            value: "v1.9.3"
          - name: GINKGO_FOCUS
            value: "\\[K8s-Upgrade\\]"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 7300m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api
      testgrid-tab-name: capi-pr-e2e-main-1-24-latest
  - name: pull-cluster-api-e2e-workload-upgrade-1-21-1-22-main
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    decorate: true
    decoration_config:
      gcs_credentials_secret: "" # Use workload identity for uploading artifacts
    optional: true
    always_run: false
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    path_alias: sigs.k8s.io/cluster-api
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
    spec:
      serviceAccountName: prowjob-default-sa
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
        args:
          - runner.sh
          - "./scripts/ci-e2e.sh"
        env:
          - name: KUBERNETES_VERSION_UPGRADE_FROM
            value: "stable-1.21"
          - name: KUBERNETES_VERSION_UPGRADE_TO
            value: "stable-1.22"
          - name: ETCD_VERSION_UPGRADE_TO
            value: "3.5.3-0"
          - name: COREDNS_VERSION_UPGRADE_TO
            value: "v1.8.4"
          - name: GINKGO_FOCUS
            value: "\\[K8s-Upgrade\\]"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 7300m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api
      testgrid-tab-name: capi-pr-e2e-main-1-21-1-22
