periodics:
- name: periodic-cluster-api-test-release-0-3
  interval: 12h
  decorate: true
  decoration_config:
    gcs_credentials_secret: "" # Use workload identity for uploading artifacts
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: release-0.3
    path_alias: sigs.k8s.io/cluster-api
  spec:
    serviceAccountName: prowjob-default-sa
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211111-d096cb0c5f-1.18
      command:
      - "./scripts/ci-test.sh"
      resources:
        requests:
          cpu: 7300m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-0.3
    testgrid-tab-name: capi-test-release-0-3
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "4"
- name: periodic-cluster-api-e2e-release-0-3
  interval: 12h
  decorate: true
  decoration_config:
    gcs_credentials_secret: "" # Use workload identity for uploading artifacts
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: release-0.3
    path_alias: sigs.k8s.io/cluster-api
  spec:
    serviceAccountName: prowjob-default-sa
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211111-d096cb0c5f-1.18
        args:
          - runner.sh
          - "./scripts/ci-e2e.sh"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 7300m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-0.3
    testgrid-tab-name: capi-e2e-release-0-3
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "4"
- name: periodic-cluster-api-verify-book-links-release-0-3
  interval: 24h
  decorate: true
  decoration_config:
    gcs_credentials_secret: "" # Use workload identity for uploading artifacts
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: release-0.3
    path_alias: sigs.k8s.io/cluster-api
  spec:
    serviceAccountName: prowjob-default-sa
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211111-d096cb0c5f-1.18
      command:
      - "runner.sh"
      - "make"
      - "verify-book-links"
      env:
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: cluster-lifecycle-github-token
            key: cluster-lifecycle-github-token
  volumes:
  - name: cluster-lifecycle-github-token
    secret:
      secretName: cluster-lifecycle-github-token
      items:
      - key: cluster-lifecycle-github-token
        path: cluster-lifecycle-github-token
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-0.3
    testgrid-tab-name: capi-verify-book-links-release-0-3
