presubmits:
  kubernetes-sigs/cluster-api:
  - name: pull-cluster-api-build-release-0-3
    decorate: true
    decoration_config:
      gcs_credentials_secret: "" # Use workload identity for uploading artifacts
    path_alias: sigs.k8s.io/cluster-api
    always_run: true
    branches:
    # The script this job runs is not in all branches.
    - ^release-0.3$
    spec:
      serviceAccountName: prowjob-default-sa
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211111-d096cb0c5f-1.18
        command:
        - runner.sh
        - ./scripts/ci-build.sh
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-0.3
      testgrid-tab-name: capi-pr-build-release-0-3
  - name: pull-cluster-api-make-release-0-3
    decorate: true
    decoration_config:
      gcs_credentials_secret: "" # Use workload identity for uploading artifacts
    path_alias: sigs.k8s.io/cluster-api
    always_run: true
    labels:
      preset-dind-enabled: "true"
    branches:
    # The script this job runs is not in all branches.
    - ^release-0.3$
    spec:
      serviceAccountName: prowjob-default-sa
      containers:
      - command:
        - runner.sh
        - ./scripts/ci-make.sh
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211111-d096cb0c5f-1.18
        resources:
          requests:
            cpu: 7300m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-0.3
      testgrid-tab-name: capi-pr-make-release-0-3
  - name: pull-cluster-api-apidiff-release-0-3
    decorate: true
    decoration_config:
      gcs_credentials_secret: "" # Use workload identity for uploading artifacts
    path_alias: sigs.k8s.io/cluster-api
    always_run: true
    optional: true
    branches:
    # The script this job runs is not in all branches.
    - ^release-0.3$
    spec:
      serviceAccountName: prowjob-default-sa
      containers:
      - command:
        - runner.sh
        - ./scripts/ci-apidiff.sh
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211111-d096cb0c5f-1.18
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-0.3
      testgrid-tab-name: capi-pr-apidiff-release-0-3
  - name: pull-cluster-api-verify-release-0-3
    decorate: true
    decoration_config:
      gcs_credentials_secret: "" # Use workload identity for uploading artifacts
    path_alias: sigs.k8s.io/cluster-api
    always_run: true
    branches:
    # The script this job runs is not in all branches.
    - ^release-0.3$
    spec:
      serviceAccountName: prowjob-default-sa
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211111-d096cb0c5f-1.18
        command:
        - "runner.sh"
        - "make"
        - "verify"
        resources:
          requests:
            cpu: 7300m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-0.3
      testgrid-tab-name: capi-pr-verify-release-0-3
  - name: pull-cluster-api-test-release-0-3
    decorate: true
    decoration_config:
      gcs_credentials_secret: "" # Use workload identity for uploading artifacts
    path_alias: sigs.k8s.io/cluster-api
    always_run: true
    branches:
    # The script this job runs is not in all branches.
    - ^release-0.3$
    spec:
      serviceAccountName: prowjob-default-sa
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211111-d096cb0c5f-1.18
        args:
        - runner.sh
        - ./scripts/ci-test.sh
        resources:
          requests:
            cpu: 7300m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-0.3
      testgrid-tab-name: capi-pr-test-release-0-3
  - name: pull-cluster-api-e2e-release-0-3
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    decorate: true
    decoration_config:
      gcs_credentials_secret: "" # Use workload identity for uploading artifacts
    branches:
    # The script this job runs is not in all branches.
    - ^release-0.3$
    path_alias: sigs.k8s.io/cluster-api
    run_if_changed: '^((api|bootstrap|cmd|config|controllers|controlplane|errors|exp|feature|hack|scripts|test|third_party|util)/|main\.go|go\.mod|go\.sum|Dockerfile|Makefile)'
    spec:
      serviceAccountName: prowjob-default-sa
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211111-d096cb0c5f-1.18
        args:
          - runner.sh
          - "./scripts/ci-e2e.sh"
        env:
          - name: GINKGO_FOCUS
            value: "\\[PR-Blocking\\]"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 7300m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-0.3
      testgrid-tab-name: capi-pr-e2e-release-0-3
  - name: pull-cluster-api-e2e-full-release-0-3
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    decorate: true
    decoration_config:
      gcs_credentials_secret: "" # Use workload identity for uploading artifacts
    optional: true
    always_run: false
    branches:
    # The script this job runs is not in all branches.
    - ^release-0.3$
    path_alias: sigs.k8s.io/cluster-api
    spec:
      serviceAccountName: prowjob-default-sa
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211111-d096cb0c5f-1.18
        args:
          - runner.sh
          - "./scripts/ci-e2e.sh"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 7300m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-0.3
      testgrid-tab-name: capi-pr-e2e-full-release-0-3
