periodics:

- name: periodic-cluster-api-e2e-workload-upgrade-1-18-1-19-release-0-4
  interval: 48h
  decorate: true
  decoration_config:
    gcs_credentials_secret: "" # Use workload identity for uploading artifacts
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: release-0.4
    path_alias: sigs.k8s.io/cluster-api
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    serviceAccountName: prowjob-default-sa
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220727-f055b40439-1.21
      args:
        - runner.sh
        - "./scripts/ci-e2e.sh"
      env:
        - name: KUBERNETES_VERSION_UPGRADE_FROM
          value: "stable-1.18"
        - name: KUBERNETES_VERSION_UPGRADE_TO
          value: "stable-1.19"
        - name: ETCD_VERSION_UPGRADE_TO
          value: "3.4.13-0"
        - name: COREDNS_VERSION_UPGRADE_TO
          value: "1.7.0"
        - name: GINKGO_FOCUS
          value: "\\[K8s-Upgrade\\]"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 7300m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-0.4
    testgrid-tab-name: capi-e2e-release-0-4-1-18-1-19
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "4"

- name: periodic-cluster-api-e2e-workload-upgrade-1-19-1-20-release-0-4
  interval: 48h
  decorate: true
  decoration_config:
    gcs_credentials_secret: "" # Use workload identity for uploading artifacts
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: release-0.4
    path_alias: sigs.k8s.io/cluster-api
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    serviceAccountName: prowjob-default-sa
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220727-f055b40439-1.21
      args:
        - runner.sh
        - "./scripts/ci-e2e.sh"
      env:
        - name: KUBERNETES_VERSION_UPGRADE_FROM
          value: "stable-1.19"
        - name: KUBERNETES_VERSION_UPGRADE_TO
          value: "stable-1.20"
        - name: ETCD_VERSION_UPGRADE_TO
          value: "3.4.13-0"
        - name: COREDNS_VERSION_UPGRADE_TO
          value: "1.7.0"
        - name: GINKGO_FOCUS
          value: "\\[K8s-Upgrade\\]"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 7300m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-0.4
    testgrid-tab-name: capi-e2e-release-0-4-1-19-1-20
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "4"

- name: periodic-cluster-api-e2e-workload-upgrade-1-20-1-21-release-0-4
  interval: 48h
  decorate: true
  decoration_config:
    gcs_credentials_secret: "" # Use workload identity for uploading artifacts
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: release-0.4
    path_alias: sigs.k8s.io/cluster-api
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    serviceAccountName: prowjob-default-sa
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220727-f055b40439-1.21
      args:
        - runner.sh
        - "./scripts/ci-e2e.sh"
      env:
        - name: KUBERNETES_VERSION_UPGRADE_FROM
          value: "stable-1.20"
        - name: KUBERNETES_VERSION_UPGRADE_TO
          value: "stable-1.21"
        - name: ETCD_VERSION_UPGRADE_TO
          value: "3.4.13-0"
        - name: COREDNS_VERSION_UPGRADE_TO
          value: "v1.8.0"
        - name: GINKGO_FOCUS
          value: "\\[K8s-Upgrade\\]"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 7300m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-0.4
    testgrid-tab-name: capi-e2e-release-0-4-1-20-1-21
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "4"

- name: periodic-cluster-api-e2e-workload-upgrade-1-21-1-22-release-0-4
  interval: 48h
  decorate: true
  decoration_config:
    gcs_credentials_secret: "" # Use workload identity for uploading artifacts
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: release-0.4
    path_alias: sigs.k8s.io/cluster-api
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    serviceAccountName: prowjob-default-sa
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220727-f055b40439-1.21
      args:
        - runner.sh
        - "./scripts/ci-e2e.sh"
      env:
        - name: KUBERNETES_VERSION_UPGRADE_FROM
          value: "stable-1.21"
        - name: KUBERNETES_VERSION_UPGRADE_TO
          value: "stable-1.22"
        - name: ETCD_VERSION_UPGRADE_TO
          value: "3.5.3-0"
        - name: COREDNS_VERSION_UPGRADE_TO
          value: "v1.8.4"
        - name: GINKGO_FOCUS
          value: "\\[K8s-Upgrade\\]"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 7300m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-0.4
    testgrid-tab-name: capi-e2e-release-0-4-1-21-1-22
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "4"

- name: periodic-cluster-api-e2e-workload-upgrade-1-22-1-23-release-0-4
  interval: 48h
  decorate: true
  decoration_config:
    gcs_credentials_secret: "" # Use workload identity for uploading artifacts
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: release-0.4
    path_alias: sigs.k8s.io/cluster-api
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    serviceAccountName: prowjob-default-sa
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220727-f055b40439-1.21
      args:
        - runner.sh
        - "./scripts/ci-e2e.sh"
      env:
        - name: KUBERNETES_VERSION_UPGRADE_FROM
          value: "stable-1.22"
        - name: KUBERNETES_VERSION_UPGRADE_TO
          value: "stable-1.23"
        - name: ETCD_VERSION_UPGRADE_TO
          value: "3.5.3-0"
        - name: COREDNS_VERSION_UPGRADE_TO
          # CAPI 0.4 only supports up to CoreDNS version 1.8.4.
          value: "v1.8.4"
        - name: GINKGO_FOCUS
          value: "\\[K8s-Upgrade\\]"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 7300m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-0.4
    testgrid-tab-name: capi-e2e-release-0-4-1-22-1-23
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "4"
