presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-files-remake
    cluster: k8s-infra-prow-build
    path_alias: "k8s.io/kubernetes"
    decorate: true
    optional: false
    run_if_changed: 'Makefile.generated_files|make-rules'
    always_run: false
    skip_report: false
    # branched per release (older go versions)
    skip_branches:
    - release-\d+.\d+ # per-release job
    annotations:
      fork-per-release: "true"
      testgrid-alert-stale-results-hours: "24"
      testgrid-create-test-group: "true"
      testgrid-num-failures-to-alert: "10"
    spec:
      containers:
      - name: main
        command:
        - make
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        args:
        - verify
        env:
        # Space separated list of the checks to run
        - name: WHAT
          value: generated-files-remake
        resources:
          limits:
            cpu: 1500m
            memory: 7Gi
          requests:
            cpu: 1500m
            memory: 7Gi
