presubmits:
  kubernetes-sigs/kube-batch:
  - name: pull-kube-batch-verify
    branches:
    - master
    always_run: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/gcloud-in-go:v20220607-33951ed1ed
        args:
        - "--repo=github.com/$(REPO_OWNER)/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--clean"
        - "--timeout=45"
        - --scenario=execute
        - --
        - make
        - verify
    annotations:
      testgrid-dashboards: presubmits-kube-batch
      testgrid-tab-name: verify
