presubmits:
  kubernetes-sigs/blob-csi-driver:
  - name: pull-blob-csi-driver-verify
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/blob-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        command:
        - runner.sh
        args:
        - make
        - verify
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: provider-azure-blobfuse-csi-driver
      testgrid-tab-name: pr-blob-csi-driver-verify
      description: "Run code verification tests for Azure Blob Storage CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-blob-csi-driver-unit
    decorate: true
    skip_if_only_changed: "^docs/|^site/|^\\.github/|\\.(md|adoc)$|^(README|LICENSE)$"
    path_alias: sigs.k8s.io/blob-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        command:
        - runner.sh
        args:
        - make
        - unit-test
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: provider-azure-blobfuse-csi-driver
      testgrid-tab-name: pr-blob-csi-driver-unit
      description: "Run unit tests for Azure Blob Storage CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-blob-csi-driver-sanity
    decorate: true
    skip_if_only_changed: "^docs/|^site/|^\\.github/|\\.(md|adoc)$|^(README|LICENSE)$"
    path_alias: sigs.k8s.io/blob-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        command:
        - runner.sh
        args:
        - make
        - sanity-test
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: provider-azure-blobfuse-csi-driver
      testgrid-tab-name: pr-blob-csi-driver-sanity
      description: "Run sanity tests for Azure Blob Storage CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-blob-csi-driver-integration
    decorate: true
    skip_if_only_changed: "^docs/|^site/|^\\.github/|\\.(md|adoc)$|^(README|LICENSE)$"
    path_alias: sigs.k8s.io/blob-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        command:
        - runner.sh
        args:
        - make
        - integration-test
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: provider-azure-blobfuse-csi-driver
      testgrid-tab-name: pr-blob-csi-driver-integration
      description: "Run integration tests for Azure Blob Storage CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-blob-csi-driver-e2e
    decorate: true
    skip_if_only_changed: "^docs/|^site/|^\\.github/|\\.(md|adoc)$|^(README|LICENSE)$"
    path_alias: sigs.k8s.io/blob-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
      workdir: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        command:
        - runner.sh
        - kubetest
        args:
        # Generic e2e test args
        - --test
        - --up
        - --down
        - --dump=$(ARTIFACTS)
        # Azure-specific test args
        - --provider=skeleton
        - --deployment=aksengine
        - --aksengine-admin-username=azureuser
        - --aksengine-creds=$(AZURE_CREDENTIALS)
        - --aksengine-orchestratorRelease=1.20
        - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
        - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/test/manifest/linux.json
        - --aksengine-download-url=https://aka.ms/aks-engine/aks-engine-k8s-e2e.tar.gz
        - --test-blob-csi-driver
        # Specific test args
        - --ginkgo-parallel=1
        - --timeout=420m
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: provider-azure-blobfuse-csi-driver
      testgrid-tab-name: pr-blob-csi-driver-e2e
      description: "Run E2E tests for Azure Blob Storage CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-blob-csi-driver-e2e-vmss
    decorate: true
    skip_if_only_changed: "^docs/|^site/|^\\.github/|\\.(md|adoc)$|^(README|LICENSE)$"
    path_alias: sigs.k8s.io/blob-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
      workdir: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        command:
        - runner.sh
        - kubetest
        args:
        # Generic e2e test args
        - --test
        - --up
        - --down
        - --dump=$(ARTIFACTS)
        # Azure-specific test args
        - --provider=skeleton
        - --deployment=aksengine
        - --aksengine-admin-username=azureuser
        - --aksengine-creds=$(AZURE_CREDENTIALS)
        - --aksengine-orchestratorRelease=1.23
        - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
        - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/test/manifest/linux-vmss.json
        - --aksengine-download-url=https://aka.ms/aks-engine/aks-engine-k8s-e2e.tar.gz
        # Specific test args
        - --test-blob-csi-driver
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: provider-azure-blobfuse-csi-driver
      testgrid-tab-name: pr-blob-csi-driver-e2e-vmss
      description: "Run E2E tests on a VMSS-based cluster for Azure Blob Storage CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-blob-csi-driver-e2e-proxy
    decorate: true
    skip_if_only_changed: "^docs/|^site/|^\\.github/|\\.(md|adoc)$|^(README|LICENSE)$"
    path_alias: sigs.k8s.io/blob-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
      workdir: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        command:
        - runner.sh
        - kubetest
        args:
        # Generic e2e test args
        - --test
        - --up
        - --down
        - --dump=$(ARTIFACTS)
        # Azure-specific test args
        - --provider=skeleton
        - --deployment=aksengine
        - --aksengine-admin-username=azureuser
        - --aksengine-creds=$(AZURE_CREDENTIALS)
        - --aksengine-orchestratorRelease=1.23
        - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
        - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/test/manifest/linux.json
        - --aksengine-download-url=https://aka.ms/aks-engine/aks-engine-k8s-e2e.tar.gz
        - --test-blob-csi-driver
        # Specific test args
        - --ginkgo-parallel=1
        - --timeout=420m
        securityContext:
          privileged: true
        env:
          - name: ENABLE_BLOBFUSE_PROXY
            value: "true"
    annotations:
      testgrid-dashboards: provider-azure-blobfuse-csi-driver
      testgrid-tab-name: pull-blob-csi-driver-e2e-proxy
      description: "Run E2E tests for Azure Blob Storage CSI driver based on blobfuse-proxy"
      testgrid-num-columns-recent: '30'
  - name: pull-blob-csi-driver-external-e2e-blobfuse
    decorate: true
    skip_if_only_changed: "^docs/|^site/|^\\.github/|\\.(md|adoc)$|^(README|LICENSE)$"
    path_alias: sigs.k8s.io/blob-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
      workdir: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        command:
        - runner.sh
        - kubetest
        args:
        # Generic e2e test args
        - --test
        - --up
        - --down
        - --dump=$(ARTIFACTS)
        # Azure-specific test args
        - --provider=skeleton
        - --deployment=aksengine
        - --aksengine-admin-username=azureuser
        - --aksengine-creds=$(AZURE_CREDENTIALS)
        - --aksengine-orchestratorRelease=1.22
        - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
        - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/test/manifest/linux.json
        - --aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/nightly/aks-engine-nightly-linux-amd64.tar.gz
        - --test-blob-csi-driver
        # Specific test args
        - --ginkgo-parallel=1
        - --timeout=420m
        securityContext:
          privileged: true
        env:
          - name: EXTERNAL_E2E_TEST_BLOBFUSE
            value: "true"
    annotations:
      testgrid-dashboards: provider-azure-blobfuse-csi-driver
      testgrid-tab-name: pr-blob-csi-driver-external-e2e-blobfuse
      description: "Run External E2E tests for Azure Blob Storage CSI driver using blobfuse."
      testgrid-num-columns-recent: '30'
  - name: pull-blob-csi-driver-external-e2e-nfs
    decorate: true
    skip_if_only_changed: "^docs/|^site/|^\\.github/|\\.(md|adoc)$|^(README|LICENSE)$"
    path_alias: sigs.k8s.io/blob-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
      workdir: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        command:
        - runner.sh
        - kubetest
        args:
        # Generic e2e test args
        - --test
        - --up
        - --down
        - --dump=$(ARTIFACTS)
        # Azure-specific test args
        - --provider=skeleton
        - --deployment=aksengine
        - --aksengine-admin-username=azureuser
        - --aksengine-creds=$(AZURE_CREDENTIALS)
        - --aksengine-orchestratorRelease=1.22
        - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
        - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/test/manifest/linux.json
        - --aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/nightly/aks-engine-nightly-linux-amd64.tar.gz
        - --test-blob-csi-driver
        # Specific test args
        - --ginkgo-parallel=1
        - --timeout=420m
        securityContext:
          privileged: true
        env:
          - name: EXTERNAL_E2E_TEST_NFS
            value: "true"
    annotations:
      testgrid-dashboards: provider-azure-blobfuse-csi-driver
      testgrid-tab-name: pr-blob-csi-driver-external-e2e-nfs
      description: "Run External E2E tests for Azure Blob Storage CSI driver using nfs."
      testgrid-num-columns-recent: '30'
  - name: pull-blob-csi-driver-e2e-capz
    decorate: true
    always_run: false
    optional: true
    path_alias: sigs.k8s.io/blob-csi-driver
    branches:
      - master
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
      preset-azure-cred-only: "true"
      preset-azure-anonymous-pull: "true"
    extra_refs:
      - org: kubernetes-sigs
        repo: cluster-api-provider-azure
        base_ref: release-1.4
        path_alias: sigs.k8s.io/cluster-api-provider-azure
        workdir: true
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
          command:
            - runner.sh
            - ./scripts/ci-entrypoint.sh
          args:
            - bash
            - -c
            - >-
              cd ${GOPATH}/src/sigs.k8s.io/blob-csi-driver &&
              make e2e-test
          securityContext:
            privileged: true
          env:
            - name: NODE_MACHINE_TYPE
              value: "Standard_D2s_v3"
    annotations:
      testgrid-dashboards: provider-azure-blobfuse-csi-driver
      testgrid-tab-name: pull-blob-csi-driver-e2e-capz
      description: "Run E2E tests on a capz cluster for Blob CSI driver."
      testgrid-num-columns-recent: '30'
