target: "gs://k8s-testgrid-canary/config"
sources:
- name: "" # Kubernetes configs can't be renamed
  location: "gs://k8s-testgrid-canary/configs/k8s/config"
- name: "google-oss"
  location: "gs://oss-prow-own-testgrid/config"
- name: "istio"
  location: "gs://istio-testgrid/config"
- name: "kubevirt"
  location: "gs://kubevirt-prow/testgrid/config"
- name: "tekton"
  location: "gs://tekton-prow/testgrid/config"
- name: "cert-manager"
  location: "gs://jetstack-testgrid/config"
- name: "gardener"
  location: "gs://gardener-prow/testgrid/config"
