# Dashboard Group

dashboard_groups:
- name: sig-release
  dashboard_names:
  - sig-release-master-blocking
  - sig-release-master-informing
  - sig-release-1.25-blocking
  - sig-release-1.25-informing
  - sig-release-1.24-blocking
  - sig-release-1.24-informing
  - sig-release-1.23-blocking
  - sig-release-1.23-informing
  - sig-release-1.22-blocking
  - sig-release-1.22-informing
  - sig-release-releng-blocking
  - sig-release-releng-informing
  - sig-release-releng-presubmits
  - sig-release-image-pushes
  - sig-release-publishing-bot
  - sig-release-release-notes-presubmits
  - sig-release-job-config-errors

# Dashboards

dashboards:
- name: sig-release-master-blocking
- name: sig-release-master-informing
- name: sig-release-1.25-blocking
- name: sig-release-1.25-informing
- name: sig-release-1.24-blocking
- name: sig-release-1.24-informing
- name: sig-release-1.23-blocking
- name: sig-release-1.23-informing
- name: sig-release-1.22-blocking
- name: sig-release-1.22-informing
- name: sig-release-releng-blocking
- name: sig-release-releng-informing
- name: sig-release-releng-presubmits
- name: sig-release-image-pushes
- name: sig-release-publishing-bot
- name: sig-release-release-notes-presubmits
  dashboard_tab:
  - name: build-dev
    test_group_name: pull-release-notes-build-dev
    base_options: width=10
  - name: build-prod
    test_group_name: pull-release-notes-build-prod
    base_options: width=10
  - name: check-prettier
    test_group_name: pull-release-notes-check-prettier
    base_options: width=10
  - name: doc
    test_group_name: pull-release-notes-doc
    base_options: width=10
  - name: e2e
    test_group_name: pull-release-notes-e2e
    base_options: width=10
  - name: lint
    test_group_name: pull-release-notes-lint
    base_options: width=10
  - name: test
    test_group_name: pull-release-notes-test
    base_options: width=10
- name: sig-release-job-config-errors
