# sigs.k8s.io/cluster-capacity presubmits
presubmits:
  kubernetes-sigs/cluster-capacity:
  - name: pull-cluster-capacity-verify-gofmt-release-1-21
    decorate: true
    path_alias: sigs.k8s.io/cluster-capacity
    branches:
    # The script this job runs is not in all branches.
    - ^release-1.21$
    always_run: true
    spec:
      containers:
      - image: golang:1.16.14
        command:
        - make
        args:
        - verify-gofmt
  - name: pull-cluster-capacity-verify-build-release-1-21
    decorate: true
    path_alias: sigs.k8s.io/cluster-capacity
    branches:
    # The script this job runs is not in all branches.
    - ^release-1.21$
    always_run: true
    spec:
      containers:
      - image: golang:1.16.14
        command:
        - make
        args:
        - build
  - name: pull-cluster-capacity-unit-test-release-1-21
    decorate: true
    path_alias: sigs.k8s.io/cluster-capacity
    branches:
    # The script this job runs is not in all branches.
    - ^release-1.21$
    always_run: true
    spec:
      containers:
      - image: golang:1.16.14
        command:
        - make
        args:
        - test-unit
  - name: pull-cluster-capacity-test-e2e-k8s-release-1-21-1-21
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-cluster-capacity-test-e2e-k8s-release-1.21-1.21
    decorate: true
    decoration_config:
      timeout: 20m
    path_alias: sigs.k8s.io/cluster-capacity
    always_run: true
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    branches:
    - release-1.21
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        command:
        # generic runner script, handles DIND, bazelrc for caching, etc.
        - runner.sh
        env:
        - name: KUBERNETES_VERSION
          value: "v1.21.2"
        - name: KIND_E2E
          value: "true"
        args:
        - make
        - test-e2e
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
  - name: pull-cluster-capacity-test-e2e-k8s-release-1-21-1-20
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-cluster-capacity-test-e2e-k8s-release-1.21-1.20
    decorate: true
    decoration_config:
      timeout: 20m
    path_alias: sigs.k8s.io/cluster-capacity
    always_run: true
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    branches:
    - release-1.21
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        command:
        # generic runner script, handles DIND, bazelrc for caching, etc.
        - runner.sh
        env:
        - name: KUBERNETES_VERSION
          value: "v1.20.7"
        - name: KIND_E2E
          value: "true"
        args:
        - make
        - test-e2e
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
  - name: pull-cluster-capacity-test-e2e-k8s-release-1-21-1-19
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-cluster-capacity-test-e2e-k8s-release-1.21-1.19
    decorate: true
    decoration_config:
      timeout: 20m
    path_alias: sigs.k8s.io/cluster-capacity
    always_run: true
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    branches:
    - release-1.21
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        command:
        # generic runner script, handles DIND, bazelrc for caching, etc.
        - runner.sh
        env:
        - name: KUBERNETES_VERSION
          value: "v1.19.7"
        - name: KIND_E2E
          value: "true"
        args:
        - make
        - test-e2e
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
