presubmits:
  kubernetes-sigs/cluster-api-provider-digitalocean:
  - name: pull-cluster-api-provider-digitalocean-test-release-1-2
    always_run: true
    optional: false
    decorate: true
    path_alias: "sigs.k8s.io/cluster-api-provider-digitalocean"
    branches:
    - ^release-1.2$
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
        command:
        - "./scripts/ci-test.sh"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-digitalocean
      testgrid-tab-name: capdo-pr-test-release-1-2
  - name: pull-cluster-api-provider-digitalocean-build-release-1-2
    always_run: true
    optional: false
    decorate: true
    path_alias: "sigs.k8s.io/cluster-api-provider-digitalocean"
    branches:
    - ^release-1.2$
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
        command:
        - "./scripts/ci-build.sh"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-digitalocean
      testgrid-tab-name: capdo-pr-build-release-1-2
  - name: pull-cluster-api-provider-digitalocean-verify-release-1-2
    always_run: true
    optional: false
    decorate: true
    path_alias: "sigs.k8s.io/cluster-api-provider-digitalocean"
    branches:
    - ^release-1.2$
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
        command:
        - make
        args:
        - verify
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-digitalocean
      testgrid-tab-name: capdo-pr-verify-release-1-2
  - name: pull-cluster-api-provider-digitalocean-lint-release-1-2
    always_run: true
    optional: false
    decorate: true
    path_alias: "sigs.k8s.io/cluster-api-provider-digitalocean"
    branches:
    - ^release-1.2$
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
        command:
        - make
        args:
        - lint
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-digitalocean
      testgrid-tab-name: capdo-pr-lint-release-1-2
  - name: pull-cluster-api-provider-digitalocean-e2e-release-1-2
    always_run: true
    optional: false
    decorate: true
    path_alias: "sigs.k8s.io/cluster-api-provider-digitalocean"
    decoration_config:
      timeout: 5h
    max_concurrency: 1
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
      preset-do-credential: "true"
    branches:
    - ^release-1.2$
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
        command:
          - "runner.sh"
          - "./scripts/ci-e2e.sh"
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 1
            memory: "4Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-digitalocean
      testgrid-tab-name: capdo-pr-e2e-release-1-2
  - name: pull-cluster-api-provider-digitalocean-capi-e2e-release-1-2
    always_run: false
    optional: true
    decorate: true
    path_alias: "sigs.k8s.io/cluster-api-provider-digitalocean"
    decoration_config:
      timeout: 5h
    max_concurrency: 1
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
      preset-do-credential: "true"
    branches:
    - ^release-1.2$
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
        command:
          - "runner.sh"
          - "./scripts/ci-e2e.sh"
        env:
          - name: GINKGO_FOCUS
            value: "Cluster API E2E tests"
          - name: GINKGO_SKIP
            value: "\\[K8s-Upgrade\\]|API Version Upgrade"
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 1
            memory: "4Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-digitalocean
      testgrid-tab-name: capdo-pr-capi-e2e-release-1-2
  - name: pull-cluster-api-provider-digitalocean-e2e-workload-upgrade-release-1-2
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
      preset-do-credential: "true"
    path_alias: "sigs.k8s.io/cluster-api-provider-digitalocean"
    branches:
    - ^release-1.2$
    always_run: false
    optional: true
    decorate: true
    decoration_config:
      timeout: 5h
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
          args:
            - runner.sh
            - "./scripts/ci-e2e.sh"
          env:
            - name: GINKGO_FOCUS
              value: "\\[K8s-Upgrade\\]"
          # we need privileged mode in order to do docker in docker
          securityContext:
            privileged: true
          resources:
            requests:
              memory: "9000Mi"
              cpu: 2000m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-digitalocean
      testgrid-tab-name: capdo-pr-e2e-upgrade-release-1-2
  - name: pull-cluster-api-provider-digitalocean-conformance-release-1-2
    always_run: false
    optional: true
    decorate: true
    path_alias: "sigs.k8s.io/cluster-api-provider-digitalocean"
    decoration_config:
      timeout: 5h
    max_concurrency: 1
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
      preset-do-credential: "true"
    branches:
    - ^release-1.2$
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
        command:
          - "runner.sh"
          - "./scripts/ci-conformance.sh"
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 2
            memory: "9Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-digitalocean
      testgrid-tab-name: capdo-pr-conformance-release-1-2
  - name: pull-cluster-api-provider-digitalocean-conformance-ci-artifacts-release-1-2
    always_run: false
    optional: true
    decorate: true
    path_alias: "sigs.k8s.io/cluster-api-provider-digitalocean"
    decoration_config:
      timeout: 5h
    max_concurrency: 1
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
      preset-do-credential: "true"
    branches:
    - ^release-1.2$
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
        command:
          - "runner.sh"
          - "./scripts/ci-conformance.sh"
        env:
          - name: E2E_ARGS
            value: "-kubetest.use-ci-artifacts"
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 2
            memory: "9Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-digitalocean
      testgrid-tab-name: capdo-pr-conformance-ci-artifacts-release-1-2
