presubmits:
  kubernetes/cloud-provider-aws:
  - name: pull-cloud-provider-aws-check
    always_run: true
    decorate: true
    skip_branches:
    - gh-pages
    path_alias: k8s.io/cloud-provider-aws
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        command:
        - runner.sh
        args:
        - make
        - check
    annotations:
      testgrid-dashboards: provider-aws-cloud-provider-aws
      testgrid-tab-name: check
      description: aws cloud provider checks
      testgrid-num-columns-recent: '30'
  - name: pull-cloud-provider-aws-test
    always_run: true
    decorate: true
    skip_branches:
    - gh-pages
    path_alias: k8s.io/cloud-provider-aws
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        command:
        - runner.sh
        args:
        - make
        - test
    annotations:
      testgrid-dashboards: provider-aws-cloud-provider-aws
      testgrid-tab-name: test
      description: aws cloud provider tests
      testgrid-num-columns-recent: '30'
  - name: pull-cloud-provider-aws-e2e
    always_run: true
    decorate: true
    skip_branches:
    - gh-pages
    path_alias: k8s.io/cloud-provider-aws
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-aws-credential-aws-oss-testing: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        command:
        - runner.sh
        args:
        - make
        - test-e2e
        - KOPS_STATE_STORE=s3://cloud-provider-aws-e2e
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: provider-aws-cloud-provider-aws
      testgrid-tab-name: e2e
      description: aws cloud provider e2e tests
      testgrid-num-columns-recent: '30'
