presets:
- labels:
    preset-cadvisor-docker-credential: "true"
  env:
  - name: DOCKER_USER
    value: /etc/cadvisor-cred/username
  - name: DOCKER_PASSWORD
    value: /etc/cadvisor-cred/password
  volumes:
  - name: cadvisor-cred
    secret:
      defaultMode: 0400
      secretName: cadvisor-docker-credential
  volumeMounts:
  - name: cadvisor-cred
    mountPath: /etc/cadvisor-cred
    readOnly: true

presubmits:
  google/cadvisor:
  - name: pull-cadvisor-e2e
    always_run: true
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
        args:
        - "--job=$(JOB_NAME)"
        - "--repo=k8s.io/kubernetes"
        - "--repo=github.com/$(REPO_OWNER)/$(REPO_NAME)=$(PULL_REFS)"
        - --root=/go/src
        - --service-account=/etc/service-account/service-account.json
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --timeout=90
        - --scenario=kubernetes_e2e
        - --
        - --deployment=node
        - --gcp-project=cadvisor-e2e
        - --gcp-zone=us-central1-f
        - --node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/containerd/image-cadvisor.yaml --test-suite=cadvisor
        - --node-tests=true
        - --provider=gce
        - --test_args=--nodes=1
        - --timeout=10m

    annotations:
      testgrid-dashboards: presubmits-misc
      testgrid-tab-name: cadvisor
periodics:
- name: ci-cadvisor-e2e
  interval: 8h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
      args:
      - --job=$(JOB_NAME)
      - --root=/go/src
      - --repo=k8s.io/kubernetes
      - --repo=github.com/google/cadvisor=master
      - --service-account=/etc/service-account/service-account.json
      - --timeout=90
      - --upload=gs://kubernetes-jenkins/logs
      - --scenario=kubernetes_e2e
      - --
      - --deployment=node
      - --gcp-project=ci-cadvisor-e2e
      - --gcp-zone=us-central1-f
      - --node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/containerd/image-cadvisor.yaml --test-suite=cadvisor
      - --node-tests=true
      - --provider=gce
      - --test_args=--nodes=1
      - --timeout=10m
      env:
      - name: GOPATH
        value: /go
  annotations:
    testgrid-dashboards: sig-node-cadvisor
    testgrid-tab-name: cadvisor-e2e
