periodics:

- name: periodic-cluster-api-provider-azure-e2e-workload-upgrade-1-21-1-22-main
  interval: 24h
  decorate: true
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-azure-cred-only: "true"
    preset-azure-anonymous-pull: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-azure
    base_ref: main
    path_alias: sigs.k8s.io/cluster-api-provider-azure
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
      args:
        - runner.sh
        - "./scripts/ci-e2e.sh"
      env:
        - name: KUBERNETES_VERSION_UPGRADE_FROM
          value: "stable-1.21"
        - name: KUBERNETES_VERSION_UPGRADE_TO
          value: "stable-1.22"
        - name: ETCD_VERSION_UPGRADE_TO
          value: "3.5.3-0"
        - name: COREDNS_VERSION_UPGRADE_TO
          value: "v1.8.4"
        - name: GINKGO_FOCUS
          value: "\\[K8s-Upgrade\\]"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 7300m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-azure
    testgrid-tab-name: capi-periodic-upgrade-main-1-21-1-22

- name: periodic-cluster-api-provider-azure-e2e-workload-upgrade-1-22-1-23-main
  interval: 24h
  decorate: true
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-azure-cred-only: "true"
    preset-azure-anonymous-pull: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-azure
    base_ref: main
    path_alias: sigs.k8s.io/cluster-api-provider-azure
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
      args:
        - runner.sh
        - "./scripts/ci-e2e.sh"
      env:
        - name: KUBERNETES_VERSION_UPGRADE_FROM
          value: "stable-1.22"
        - name: KUBERNETES_VERSION_UPGRADE_TO
          value: "stable-1.23"
        - name: ETCD_VERSION_UPGRADE_TO
          value: "3.5.3-0"
        - name: COREDNS_VERSION_UPGRADE_TO
          value: "v1.8.6"
        - name: GINKGO_FOCUS
          value: "\\[K8s-Upgrade\\]"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 7300m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-azure
    testgrid-tab-name: capi-periodic-upgrade-main-1-22-1-23

- name: periodic-cluster-api-provider-azure-e2e-workload-upgrade-1-23-1-24-main
  interval: 24h
  decorate: true
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-azure-cred-only: "true"
    preset-azure-anonymous-pull: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-azure
    base_ref: main
    path_alias: sigs.k8s.io/cluster-api-provider-azure
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
      args:
        - runner.sh
        - "./scripts/ci-e2e.sh"
      env:
        - name: KUBERNETES_VERSION_UPGRADE_FROM
          value: "stable-1.23"
        - name: KUBERNETES_VERSION_UPGRADE_TO
          value: "stable-1.24"
        - name: ETCD_VERSION_UPGRADE_TO
          value: "3.5.3-0"
        - name: COREDNS_VERSION_UPGRADE_TO
          value: "v1.8.6"
        - name: GINKGO_FOCUS
          value: "\\[K8s-Upgrade\\]"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 7300m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-azure
    testgrid-tab-name: capi-periodic-upgrade-main-1-23-1-24
