periodics:
  - interval: 6h
    name: check-dependency-stats-periodical
    cluster: k8s-infra-prow-build
    decorate: true
    decoration_config:
      timeout: 5m
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
    spec:
      containers:
      - image: golang
        command:
        - /bin/bash
        args:
        - -c
        - |
          set -euo pipefail

          export WORKDIR=${ARTIFACTS:-$TMPDIR}
          export PATH=$PATH:$GOPATH/bin

          mkdir -p "${WORKDIR}"
          pushd "$WORKDIR"
          go install github.com/kubernetes-sigs/depstat@latest
          popd

          depstat stats -m "k8s.io/kubernetes$(ls staging/src/k8s.io | awk '{printf ",k8s.io/" $0}')" --json | tee "${WORKDIR}/stats-base.json";
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
    annotations:
      testgrid-create-test-group: "true"
      testgrid-dashboards: sig-testing-misc
      description: Generates dependency statistics by running depstat for base periodically
