periodics:
- interval: 24h
  name: ci-dualstack-azure-e2e-1-21
  decorate: true
  decoration_config:
    timeout: 5h
  labels:
    preset-service-account: "true"
    preset-azure-cred: "true"
    preset-dind-enabled: "true"
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: release-1.21
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220727-f055b40439-1.21
      command:
      - runner.sh
      - kubetest
      args:
      # Generic e2e test args
      - --test
      - --up
      - --down
      - --build=quick
      - --dump=$(ARTIFACTS)
      # Azure-specific test args
      - --provider=skeleton
      - --deployment=aksengine
      - --aksengine-agentpoolcount=2
      - --aksengine-admin-username=azureuser
      - --aksengine-creds=$(AZURE_CREDENTIALS)
      - --aksengine-orchestratorRelease=1.21
      - --aksengine-mastervmsize=Standard_DS2_v2
      - --aksengine-agentvmsize=Standard_D4s_v3
      - --aksengine-deploy-custom-k8s
      - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
      - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/tests/k8s-azure/manifest/linux-dual-stack-ipvs-kubenet-1.23.json
      - --aksengine-download-url=https://aka.ms/aks-engine/aks-engine-k8s-e2e.tar.gz
      # Skipping "Should recreate evicted statefulset" because of an issue in dockershim for dualstack
      # Suggested fix - https://github.com/kubernetes/kubernetes/pull/94382
      # Skipping "HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol" because of kubenet bug in HostPort impl
      # Skipping Feature:SCTPConnectivity tests because the vhd used for tests doesn't have sctp enabled
      - --test_args=--ginkgo.focus=\[Feature:IPv6DualStack\]|\[Conformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|\[Flaky\]|\[Feature:SCTPConnectivity\]|Should.recreate.evicted.statefulset|HostPort.validates.that.there.is.no.conflict.between.pods.with.same.hostPort.but.different.hostIP.and.protocol|should.have.ipv4.and.ipv6.node.podCIDRs
      - --ginkgo-parallel=1
      securityContext:
        privileged: true
  annotations:
    testgrid-dashboards: sig-network-dualstack-azure-e2e, provider-azure-dualstack, provider-azure-1.21-signal
    testgrid-tab-name: dualstack-azure-e2e-1-21
    testgrid-alert-email: kubernetes-provider-azure@googlegroups.com
    description: "Dual-stack e2e tests on a 1.21 Kubernetes cluster provided by aks-engine (https://github.com/Azure/aks-engine) on Azure cloud"
- interval: 24h
  name: ci-dualstack-azure-e2e-1-22
  decorate: true
  decoration_config:
    timeout: 5h
  labels:
    preset-service-account: "true"
    preset-azure-cred: "true"
    preset-dind-enabled: "true"
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: release-1.22
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.22
      command:
      - runner.sh
      - kubetest
      args:
      # Generic e2e test args
      - --test
      - --up
      - --down
      - --build=quick
      - --dump=$(ARTIFACTS)
      # Azure-specific test args
      - --provider=skeleton
      - --deployment=aksengine
      - --aksengine-agentpoolcount=2
      - --aksengine-admin-username=azureuser
      - --aksengine-creds=$(AZURE_CREDENTIALS)
      - --aksengine-orchestratorRelease=1.22
      - --aksengine-mastervmsize=Standard_DS2_v2
      - --aksengine-agentvmsize=Standard_D4s_v3
      - --aksengine-deploy-custom-k8s
      - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
      - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/tests/k8s-azure/manifest/linux-dual-stack-ipvs-kubenet-1.23.json
      - --aksengine-download-url=https://aka.ms/aks-engine/aks-engine-k8s-e2e.tar.gz
      # Skipping "Should recreate evicted statefulset" because of an issue in dockershim for dualstack
      # Suggested fix - https://github.com/kubernetes/kubernetes/pull/94382
      # Skipping "HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol" because of kubenet bug in HostPort impl
      # Skipping Feature:SCTPConnectivity tests because the vhd used for tests doesn't have sctp enabled
      - --test_args=--ginkgo.focus=\[Feature:IPv6DualStack\]|\[Conformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|\[Flaky\]|\[Feature:SCTPConnectivity\]|Should.recreate.evicted.statefulset|HostPort.validates.that.there.is.no.conflict.between.pods.with.same.hostPort.but.different.hostIP.and.protocol|should.have.ipv4.and.ipv6.node.podCIDRs
      - --ginkgo-parallel=1
      securityContext:
        privileged: true
  annotations:
    testgrid-dashboards: sig-network-dualstack-azure-e2e, provider-azure-dualstack, provider-azure-1.22-signal
    testgrid-tab-name: dualstack-azure-e2e-1-22
    testgrid-alert-email: kubernetes-provider-azure@googlegroups.com
    description: "Dual-stack e2e tests on a 1.22 Kubernetes cluster provided by aks-engine (https://github.com/Azure/aks-engine) on Azure cloud"
- interval: 24h
  name: ci-dualstack-azure-e2e-1-23
  decorate: true
  decoration_config:
    timeout: 5h
  labels:
    preset-service-account: "true"
    preset-azure-cred: "true"
    preset-dind-enabled: "true"
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: release-1.23
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.23
      command:
      - runner.sh
      - kubetest
      args:
      # Generic e2e test args
      - --test
      - --up
      - --down
      - --build=quick
      - --dump=$(ARTIFACTS)
      # Azure-specific test args
      - --provider=skeleton
      - --deployment=aksengine
      - --aksengine-agentpoolcount=2
      - --aksengine-admin-username=azureuser
      - --aksengine-creds=$(AZURE_CREDENTIALS)
      - --aksengine-orchestratorRelease=1.23
      - --aksengine-mastervmsize=Standard_DS2_v2
      - --aksengine-agentvmsize=Standard_D4s_v3
      - --aksengine-deploy-custom-k8s
      - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
      - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/tests/k8s-azure/manifest/linux-dual-stack-ipvs-kubenet-1.23.json
      - --aksengine-download-url=https://aka.ms/aks-engine/aks-engine-k8s-e2e.tar.gz
      # Skipping "Should recreate evicted statefulset" because of an issue in dockershim for dualstack
      # Suggested fix - https://github.com/kubernetes/kubernetes/pull/94382
      # Skipping "HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol" because of kubenet bug in HostPort impl
      # Skipping Feature:SCTPConnectivity tests because the vhd used for tests doesn't have sctp enabled
      - --test_args=--ginkgo.focus=\[Feature:IPv6DualStack\]|\[Conformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|\[Flaky\]|\[Feature:SCTPConnectivity\]|Should.recreate.evicted.statefulset|HostPort.validates.that.there.is.no.conflict.between.pods.with.same.hostPort.but.different.hostIP.and.protocol
      - --ginkgo-parallel=1
      securityContext:
        privileged: true
  annotations:
    testgrid-dashboards: sig-network-dualstack-azure-e2e, provider-azure-dualstack, provider-azure-1.23-signal
    testgrid-tab-name: dualstack-azure-e2e-1-23
    testgrid-alert-email: kubernetes-provider-azure@googlegroups.com
    description: "Dual-stack e2e tests on a 1.23 Kubernetes cluster provided by aks-engine (https://github.com/Azure/aks-engine) on Azure cloud"
- interval: 24h
  name: ci-dualstack-azure-e2e-1-24-iptables
  decorate: true
  decoration_config:
    timeout: 5h
  labels:
    preset-service-account: "true"
    preset-azure-cred: "true"
    preset-dind-enabled: "true"
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: release-1.24
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
      command:
      - runner.sh
      - kubetest
      args:
      # Generic e2e test args
      - --test
      - --up
      - --down
      - --build=quick
      - --dump=$(ARTIFACTS)
      # Azure-specific test args
      - --provider=skeleton
      - --deployment=aksengine
      - --aksengine-agentpoolcount=2
      - --aksengine-admin-username=azureuser
      - --aksengine-creds=$(AZURE_CREDENTIALS)
      - --aksengine-orchestratorRelease=1.24
      - --aksengine-mastervmsize=Standard_DS2_v2
      - --aksengine-agentvmsize=Standard_D4s_v3
      - --aksengine-deploy-custom-k8s
      - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
      - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/tests/k8s-azure/manifest/linux-dual-stack-iptables-kubenet.json
      - --aksengine-download-url=https://aka.ms/aks-engine/aks-engine-k8s-e2e.tar.gz
      # Skipping "Should recreate evicted statefulset" because of an issue in dockershim for dualstack
      # Suggested fix - https://github.com/kubernetes/kubernetes/pull/94382
      # Skipping "HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol" because of kubenet bug in HostPort impl
      # Skipping Feature:SCTPConnectivity tests because the vhd used for tests doesn't have sctp enabled
      - --test_args=--ginkgo.focus=\[Feature:IPv6DualStack\]|\[Conformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|\[Flaky\]|\[Feature:SCTPConnectivity\]|Should.recreate.evicted.statefulset|HostPort.validates.that.there.is.no.conflict.between.pods.with.same.hostPort.but.different.hostIP.and.protocol
      - --ginkgo-parallel=1
      securityContext:
        privileged: true
  annotations:
    testgrid-dashboards: sig-network-dualstack-azure-e2e, provider-azure-dualstack, provider-azure-1.24-signal
    testgrid-tab-name: dualstack-azure-e2e-1-24-iptables
    testgrid-alert-email: kubernetes-provider-azure@googlegroups.com
    description: "Dual-stack and Conformance e2e tests on a Kubernetes cluster provided by aks-engine (https://github.com/Azure/aks-engine) on Azure cloud in iptables mode"
- interval: 24h
  name: ci-dualstack-azure-e2e-1-24-ipvs
  decorate: true
  decoration_config:
    timeout: 5h
  labels:
    preset-service-account: "true"
    preset-azure-cred: "true"
    preset-dind-enabled: "true"
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: release-1.24
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-1.24
      command:
      - runner.sh
      - kubetest
      args:
      # Generic e2e test args
      - --test
      - --up
      - --down
      - --build=quick
      - --dump=$(ARTIFACTS)
      # Azure-specific test args
      - --provider=skeleton
      - --deployment=aksengine
      - --aksengine-agentpoolcount=2
      - --aksengine-admin-username=azureuser
      - --aksengine-creds=$(AZURE_CREDENTIALS)
      - --aksengine-orchestratorRelease=1.24
      - --aksengine-mastervmsize=Standard_DS2_v2
      - --aksengine-agentvmsize=Standard_D4s_v3
      - --aksengine-deploy-custom-k8s
      - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
      - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/tests/k8s-azure/manifest/linux-dual-stack-ipvs-kubenet.json
      - --aksengine-download-url=https://aka.ms/aks-engine/aks-engine-k8s-e2e.tar.gz
      # Skipping "Should recreate evicted statefulset" because of an issue in dockershim for dualstack
      # Suggested fix - https://github.com/kubernetes/kubernetes/pull/94382
      # Skipping "HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol" because of kubenet bug in HostPort impl
      # Skipping Feature:SCTPConnectivity tests because the vhd used for tests doesn't have sctp enabled
      - --test_args=--ginkgo.focus=\[Feature:IPv6DualStack\]|\[Conformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|\[Flaky\]|\[Feature:SCTPConnectivity\]|Should.recreate.evicted.statefulset|HostPort.validates.that.there.is.no.conflict.between.pods.with.same.hostPort.but.different.hostIP.and.protocol
      - --ginkgo-parallel=1
      securityContext:
        privileged: true
  annotations:
    testgrid-dashboards: sig-network-dualstack-azure-e2e, provider-azure-dualstack, provider-azure-1.24-signal
    testgrid-tab-name: dualstack-azure-e2e-1-24-ipvs
    testgrid-alert-email: kubernetes-provider-azure@googlegroups.com
    description: "Dual-stack and Conformance e2e tests on a Kubernetes cluster provided by aks-engine (https://github.com/Azure/aks-engine) on Azure cloud in ipvs mode"
