periodics:
- interval: 3h
  cluster: k8s-infra-prow-build
  name: ci-cloud-provider-gcp-conformance-latest
  decorate: true
  decoration_config:
    timeout: 150m
  annotations:
    testgrid-tab-name: Conformance - Cloud Provider GCP - master
    testgrid-dashboards: provider-gcp-periodics
    description: Runs conformance tests using kubetest2 against cloud-provider-gcp master on GCE
  labels:
    preset-dind-enabled: "true"
    preset-k8s-ssh: "true"
    preset-service-account: "true"
  extra_refs:
  - org: kubernetes
    repo: cloud-provider-gcp
    base_ref: master
    path_alias: k8s.io/cloud-provider-gcp
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
      resources:
        limits:
          cpu: 4
          memory: 14Gi
        requests:
          cpu: 4
          memory: 14Gi
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      command:
      - runner.sh
      args:
      - "/bin/bash"
      - "-c"
      # TODO: Use published release tars for cloud-provider-gcp if/once they exist
      - set -o errexit;
        set -o nounset;
        set -o pipefail;
        set -o xtrace;
        REPO_ROOT=$GOPATH/src/k8s.io/cloud-provider-gcp;
        cd;
        export GO111MODULE=on;
        go install sigs.k8s.io/kubetest2@latest;
        go install sigs.k8s.io/kubetest2/kubetest2-gce@latest;
        go install sigs.k8s.io/kubetest2/kubetest2-tester-ginkgo@latest;
        kubetest2 gce -v 2 --repo-root $REPO_ROOT --build --up --down --test=ginkgo --master-size n1-standard-2  -- --test-package-version=v1.24.2 --focus-regex='\[Conformance\]'
- interval: 24h
  cluster: k8s-infra-prow-build
  name: ci-cloud-provider-gcp-e2e-latest
  decorate: true
  decoration_config:
    timeout: 80m
  annotations:
    testgrid-tab-name: E2E Full - Cloud Provider GCP - master
    testgrid-dashboards: provider-gcp-periodics
    description: Runs e2e-full tests using kubetest2 against cloud-provider-gcp master on GCE
  labels:
    preset-dind-enabled: "true"
    preset-k8s-ssh: "true"
    preset-service-account: "true"
  extra_refs:
  - org: kubernetes
    repo: cloud-provider-gcp
    base_ref: master
    path_alias: k8s.io/cloud-provider-gcp
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220812-a0f1ed2b84-master
      resources:
        limits:
          cpu: 4
          memory: 14Gi
        requests:
          cpu: 4
          memory: 14Gi
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      command:
      - runner.sh
      args:
      - "/bin/bash"
      - "-c"
      # TODO: Use published release tars for cloud-provider-gcp if/once they exist
      - set -o errexit;
        set -o nounset;
        set -o pipefail;
        set -o xtrace;
        REPO_ROOT=$GOPATH/src/k8s.io/cloud-provider-gcp;
        cd;
        export GO111MODULE=on;
        go install sigs.k8s.io/kubetest2@latest;
        go install sigs.k8s.io/kubetest2/kubetest2-gce@latest;
        go install sigs.k8s.io/kubetest2/kubetest2-tester-ginkgo@latest;
          kubetest2 gce -v 2 --repo-root $REPO_ROOT --build --up --down --test=ginkgo --node-size n1-standard-4 --master-size n1-standard-8 -- --test-package-version=v1.24.2 --parallel=30 --test-args='--minStartupPods=8 --ginkgo.flakeAttempts=3' --skip-regex='\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]'
