#cloud-config

runcmd:
  - echo "Test run from /tmp folder, remounting it"
  - mount /tmp /tmp -o remount,exec,suid

  - echo "This will configure built-in containerd for k8s tests. Containerd version is:"
  - ctr version # current version of containerd

  - echo "Download and install CNI configuration to /home/containerd"
  - mkdir -p /home/containerd
  - mount --bind /home/containerd /home/containerd
  - mount -o remount,exec /home/containerd
  - 'curl --fail --retry 5 --retry-delay 3 --silent --show-error -H "X-Google-Metadata-Request: True" -o /home/containerd/cni.template http://metadata.google.internal/computeMetadata/v1/instance/attributes/cni-template'

  - echo "Download and install CNI to /home/containerd"
  - 'curl -sSL --fail --retry 5 --retry-delay 3 --silent --show-error -o /home/containerd/cni.tgz https://github.com/containernetworking/plugins/releases/download/v1.0.1/cni-plugins-linux-amd64-v1.0.1.tgz'
  - tar xzf /home/containerd/cni.tgz -C /home/containerd --overwrite

  - echo "Set containerd configuration"
  - mkdir -p /etc/containerd
  - 'curl --fail --retry 5 --retry-delay 3 --silent --show-error -H "X-Google-Metadata-Request: True" -o /etc/containerd/config.toml http://metadata.google.internal/computeMetadata/v1/instance/attributes/containerd-config'

  - echo "Restarting containerd"
  - systemctl restart containerd

  - echo "Configuration complete"
