dashboard_groups:
- name: presubmits
  dashboard_names:
  - presubmits-alibaba-cloud-csi-driver
  - presubmits-cloud-provider-alibaba
  - presubmits-cloud-provider-vsphere-blocking
  - presubmits-kops
  - presubmits-kube-batch
  - presubmits-kubernetes-blocking
  - presubmits-kubernetes-nonblocking
  - presubmits-kubernetes-scalability
  - presubmits-misc
  - presubmits-node-problem-detector
  - presubmits-test-infra

dashboards:
- name: presubmits-alibaba-cloud-csi-driver
- name: presubmits-cloud-provider-alibaba
- name: presubmits-cloud-provider-vsphere-blocking
- name: presubmits-kops
- name: presubmits-kube-batch
- name: presubmits-kubernetes-blocking
  dashboard_tab:
  - name: pull-kubernetes-e2e-kind
    test_group_name: pull-kubernetes-e2e-kind
    base_options: width=10
    alert_options:
      alert_mail_to_addresses: bentheelder+alerts@google.com, antonio.ojea.garcia@gmail.com
  - name: pull-kubernetes-e2e-kind-ipv6
    test_group_name: pull-kubernetes-e2e-kind-ipv6
    base_options: width=10
    alert_options:
      alert_mail_to_addresses: bentheelder+alerts@google.com, antonio.ojea.garcia@gmail.com
  - name: pull-kubernetes-e2e-gce-100-performance
    test_group_name: pull-kubernetes-e2e-gce-100-performance
    base_options: width=10
  - name: pull-kubernetes-node-e2e-containerd
    test_group_name: pull-kubernetes-node-e2e-containerd
    base_options: width=10
  - name: pull-kubernetes-integration
    test_group_name: pull-kubernetes-integration
    base_options: width=10
  - name: pull-kubernetes-verify
    test_group_name: pull-kubernetes-verify
    base_options: width=10
  - name: pull-kubernetes-typecheck
    test_group_name: pull-kubernetes-typecheck
    base_options: width=10
  - name: pull-kubernetes-dependencies
    test_group_name: pull-kubernetes-dependencies
    base_options: width=10
  - name: pull-kubernetes-e2e-gce-network-proxy-http-connect
    test_group_name: pull-kubernetes-e2e-gce-network-proxy-http-connect
    base_options: width=10
  - name: pull-kubernetes-conformance-kind-ga-only-parallel
    test_group_name: pull-kubernetes-conformance-kind-ga-only-parallel
    base_options: width=10
  - name: pull-kubernetes-e2e-gce-ubuntu-containerd
    test_group_name: pull-kubernetes-e2e-gce-ubuntu-containerd
    base_options: width=10
  - name: pull-kubernetes-verify-govet-levee
    test_group_name: pull-kubernetes-verify-govet-levee
    base_options: width=10
  - name: pull-kubernetes-files-remake
    test_group_name: pull-kubernetes-files-remake
    base_options: width=10
- name: presubmits-kubernetes-nonblocking
  dashboard_tab:
  - name: pull-kubernetes-e2e-gce-network-proxy-grpc
    test_group_name: pull-kubernetes-e2e-gce-network-proxy-grpc
    base_options: width=10
  - name: pull-kubernetes-e2e-gce-canary
    test_group_name: pull-kubernetes-e2e-gce-canary
    base_options: width=10
  - name: pull-kubernetes-e2e-gce-ubuntu
    test_group_name: pull-kubernetes-e2e-gce-ubuntu
    base_options: width=10
  - name: pull-kubernetes-e2e-kind-canary
    test_group_name: pull-kubernetes-e2e-kind-canary
    base_options: width=10
  - name: pull-kubernetes-e2e-kind-ipv6-canary
    test_group_name: pull-kubernetes-e2e-kind-ipv6-canary
    base_options: width=10
  - name: pull-kubernetes-e2e-kind-dual-canary
    test_group_name: pull-kubernetes-e2e-kind-dual-canary
    base_options: width=10
  - name: pull-kubernetes-e2e-kind-ipvs-dual-canary
    test_group_name: pull-kubernetes-e2e-kind-ipvs-dual-canary
    base_options: width=10
  - name: pull-kubernetes-e2e-gce-alpha-features
    test_group_name: pull-kubernetes-e2e-gce-alpha-features
    base_options: width=10
  - name: pull-kubernetes-e2e-gce-storage-slow
    test_group_name: pull-kubernetes-e2e-gce-storage-slow
    base_options: width=10
  - name: pull-kubernetes-e2e-gce-storage-snapshot
    test_group_name: pull-kubernetes-e2e-gce-storage-snapshot
    base_options: width=10
  - name: pull-kubernetes-e2e-gce-csi-serial
    test_group_name: pull-kubernetes-e2e-gce-csi-serial
    base_options: width=10
  - name: pull-kubernetes-e2e-gce-device-plugin-gpu
    test_group_name: pull-kubernetes-e2e-gce-device-plugin-gpu
    base_options: width=10
  - name: pull-kubernetes-node-e2e-containerd-features
    test_group_name: pull-kubernetes-node-e2e-containerd-features
    base_options: width=10
  - name: pull-kubernetes-e2e-kops-aws
    test_group_name: pull-kubernetes-e2e-kops-aws
    base_options: width=10
  - name: pull-kubernetes-e2e-gce-storage-disruptive
    test_group_name: pull-kubernetes-e2e-gce-storage-disruptive
    base_options: width=10
  - name: pull-kubernetes-cross
    test_group_name: pull-kubernetes-cross
    base_options: width=10
  - name: pull-kubernetes-e2e-gce
    test_group_name: pull-kubernetes-e2e-gce
    base_options: width=10
  - name: pull-kubernetes-node-e2e-kubetest2
    test_group_name: pull-kubernetes-node-e2e-kubetest2
    base_options: width=10
  - name: pull-kubernetes-node-e2e-containerd-kubetest2
    test_group_name: pull-kubernetes-node-e2e-containerd-kubetest2
    base_options: width=10
  - name: pull-kubernetes-node-e2e-containerd-features-kubetest2
    test_group_name: pull-kubernetes-node-e2e-containerd-features-kubetest2
    base_options: width=10
- name: presubmits-kubernetes-scalability
- name: presubmits-misc
- name: presubmits-node-problem-detector
- name: presubmits-test-infra
